"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
import type { CommonCode } from "@/lib/server/common-codes";
import type { CalendarEvent } from "@/lib/server/calendar";

const hours=Array.from({length:24},(_,index)=>String(index).padStart(2,"0"));
const minutes=["00","10","20","30","40","50"];
function localInput(value:string|undefined,fallback:string){if(!value)return fallback;const d=new Date(value),pad=(n:number)=>String(n).padStart(2,"0");return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;}
function shifted(value:string,milliseconds:number){const date=new Date(value);if(Number.isNaN(date.getTime()))return value;date.setTime(date.getTime()+milliseconds);const pad=(n:number)=>String(n).padStart(2,"0");return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}T${pad(date.getHours())}:${pad(date.getMinutes())}`;}
function replacePart(value:string,part:"date"|"hour"|"minute",next:string){const date=value.slice(0,10),hour=value.slice(11,13),minute=value.slice(14,16);if(part==="date")return `${next}T${hour}:${minute}`;if(part==="hour")return `${date}T${next}:${minute}`;return `${date}T${hour}:${next}`;}
function DateTimePicker({label,value,onChange}:{label:string;value:string;onChange:(value:string)=>void}){return <label>{label}<div className="calendar-time-picker"><input aria-label={`${label} 날짜`} type="date" value={value.slice(0,10)} onChange={e=>onChange(replacePart(value,"date",e.target.value))} required/><select aria-label={`${label} 시간`} value={value.slice(11,13)} onChange={e=>onChange(replacePart(value,"hour",e.target.value))}>{hours.map(hour=><option value={hour} key={hour}>{hour}시</option>)}</select><select aria-label={`${label} 분`} value={value.slice(14,16)} onChange={e=>onChange(replacePart(value,"minute",e.target.value))}>{minutes.map(minute=><option value={minute} key={minute}>{minute}분</option>)}</select></div></label>}

export function CalendarEventForm({areas,event,selectedDate,returnUrl}:{areas:CommonCode[];event?:CalendarEvent|null;selectedDate:string;returnUrl:string}){
  const router=useRouter();const [pending,setPending]=useState(false),[message,setMessage]=useState("");
  const initialStart=localInput(event?.startAt,`${selectedDate}T09:00`),initialEnd=localInput(event?.endAt,`${selectedDate}T10:00`);
  const [startAt,setStartAt]=useState(initialStart),[endAt,setEndAt]=useState(initialEnd);
  function changeStart(next:string){const currentDuration=Math.max(600000,new Date(endAt).getTime()-new Date(startAt).getTime()||3600000);setStartAt(next);setEndAt(shifted(next,event?currentDuration:3600000));}
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setPending(true);setMessage("");const d=new FormData(e.currentTarget),v=(n:string)=>String(d.get(n)??"");const response=await fetch(event?`/api/v1/calendar-events/${event.id}`:"/api/v1/calendar-events",{method:event?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title:v("title"),description:v("description"),eventType:v("eventType"),startAt:new Date(startAt).toISOString(),endAt:new Date(endAt).toISOString(),allDay:d.get("allDay")==="on",areaCodeId:v("areaCodeId")||null,location:v("location")})});const payload=await response.json().catch(()=>null);setPending(false);if(!response.ok){setMessage(payload?.error?.message??"일정을 저장하지 못했습니다.");return;}router.push(returnUrl);router.refresh();}
  return <form className="calendar-event-form" onSubmit={submit}><div className="form-grid triple"><label>일정명<input name="title" defaultValue={event?.title} required maxLength={200}/></label><label>유형<select name="eventType" defaultValue={event?.eventType??"work"}><option value="meeting">회의</option><option value="milestone">마일스톤</option><option value="work">업무</option><option value="other">기타</option></select></label><label>관련 영역<select name="areaCodeId" defaultValue={event?.areaCodeId??""}><option value="">전체</option>{areas.map(a=><option value={a.id} key={a.id}>{a.label}</option>)}</select></label><DateTimePicker label="시작일시" value={startAt} onChange={changeStart}/><DateTimePicker label="종료일시" value={endAt} onChange={setEndAt}/><label>장소<input name="location" defaultValue={event?.location} maxLength={200}/></label></div><label className="toggle calendar-all-day"><input name="allDay" type="checkbox" defaultChecked={event?.allDay}/> 종일 일정</label><label>설명<textarea name="description" rows={2} defaultValue={event?.description}/></label>{message&&<p className="form-error">{message}</p>}<div className="topbar-actions"><button className="button primary" disabled={pending}>{pending?"저장 중…":event?"일정 수정":"일정 등록"}</button>{event&&<button className="button secondary" type="button" onClick={()=>router.push(returnUrl)}>수정 취소</button>}</div></form>;
}
