import "server-only";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { getDocument, listDocuments, nowIso, projectCollection, writeAuditLog } from "@/lib/server/db";
import type { CommonCode } from "@/lib/server/common-codes";

export type CalendarEvent={id:string;source:"schedule"|"progress"|"next_plan"|"issue";title:string;description:string;eventType:string;startAt:string;endAt:string;date:string;startTime:string;endTime:string;allDay:boolean;areaCodeId:string|null;areaLabel:string|null;location:string;editable:boolean;sourceUrl:string|null};
type StoredCalendarEvent={id:string;title:string;description:string;eventType:string;startAt:string;endAt:string;allDay:boolean;areaCodeId:string|null;location:string;createdBy:string;version:number;createdAt:string;updatedAt:string};
type ProgressSource={id:string;taskName:string;planDetail:string;planTargetDate:string|null;nextPlan:string;nextTargetDate:string|null;areaCodeId:string};
type ItemSource={id:string;title:string;description:string;createdAt:string;trackCodeId:string;archivedAt:string|null};
const eventSchema=z.object({title:z.string().trim().min(1).max(200),description:z.string().max(10000),eventType:z.enum(["meeting","milestone","work","other"]),startAt:z.string().datetime(),endAt:z.string().datetime(),allDay:z.boolean(),areaCodeId:z.string().uuid().nullable(),location:z.string().trim().max(200)}).superRefine((d,ctx)=>{if(d.endAt<d.startAt)ctx.addIssue({code:"custom",path:["endAt"],message:"종료일시는 시작일시 이후여야 합니다."});for(const field of ["startAt","endAt"] as const){const date=new Date(d[field]);if(date.getUTCMinutes()%10!==0||date.getUTCSeconds()!==0)ctx.addIssue({code:"custom",path:[field],message:"시간은 10분 단위로 입력해 주세요."});}});

function parts(value:string){const formatted=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(new Date(value));const part=(type:string)=>formatted.find(v=>v.type===type)?.value??"";return {date:`${part("year")}-${part("month")}-${part("day")}`,time:`${part("hour")}:${part("minute")}`};}
function inRange(date:string,from:string,to:string){return date>=from&&date<=to;}

export async function listCalendarEvents(projectId:string,from:string,to:string){
  const [events,progress,items,codes]=await Promise.all([listDocuments<StoredCalendarEvent>(projectId,"calendarEvents"),listDocuments<ProgressSource>(projectId,"weeklyProgress"),listDocuments<ItemSource>(projectId,"items"),listDocuments<CommonCode>(projectId,"commonCodes")]);
  const labels=new Map(codes.map(code=>[code.id,code.label]));const rows:CalendarEvent[]=[];
  for(const event of events){const start=parts(event.startAt),end=parts(event.endAt);if(start.date<=to&&end.date>=from)rows.push({id:event.id,source:"schedule",title:event.title,description:event.description,eventType:event.eventType,startAt:event.startAt,endAt:event.endAt,date:start.date,startTime:start.time,endTime:end.time,allDay:event.allDay,areaCodeId:event.areaCodeId,areaLabel:event.areaCodeId?labels.get(event.areaCodeId)??null:null,location:event.location,editable:true,sourceUrl:null});}
  for(const row of progress){if(row.planTargetDate&&inRange(row.planTargetDate,from,to))rows.push({id:row.id,source:"progress",title:row.taskName,description:row.planDetail,eventType:"milestone",startAt:`${row.planTargetDate}T00:00:00.000Z`,endAt:`${row.planTargetDate}T00:00:00.000Z`,date:row.planTargetDate,startTime:"",endTime:"",allDay:true,areaCodeId:row.areaCodeId,areaLabel:labels.get(row.areaCodeId)??null,location:"",editable:false,sourceUrl:`/weekly-progress?edit=${row.id}`});if(row.nextTargetDate&&inRange(row.nextTargetDate,from,to))rows.push({id:row.id,source:"next_plan",title:row.taskName,description:row.nextPlan,eventType:"work",startAt:`${row.nextTargetDate}T00:00:00.000Z`,endAt:`${row.nextTargetDate}T00:00:00.000Z`,date:row.nextTargetDate,startTime:"",endTime:"",allDay:true,areaCodeId:row.areaCodeId,areaLabel:labels.get(row.areaCodeId)??null,location:"",editable:false,sourceUrl:`/weekly-progress?edit=${row.id}`});}
  for(const item of items){const date=parts(item.createdAt);if(!item.archivedAt&&inRange(date.date,from,to))rows.push({id:item.id,source:"issue",title:item.title,description:item.description,eventType:"other",startAt:item.createdAt,endAt:item.createdAt,date:date.date,startTime:date.time,endTime:date.time,allDay:false,areaCodeId:item.trackCodeId,areaLabel:labels.get(item.trackCodeId)??null,location:"",editable:false,sourceUrl:`/items/${item.id}`});}
  return rows.sort((a,b)=>a.startAt.localeCompare(b.startAt));
}
export async function getCalendarEvent(projectId:string,id:string){const event=await getDocument<StoredCalendarEvent>(projectId,"calendarEvents",id);if(!event)return null;const codes=await listDocuments<CommonCode>(projectId,"commonCodes"),start=parts(event.startAt),end=parts(event.endAt);return {id:event.id,source:"schedule",title:event.title,description:event.description,eventType:event.eventType,startAt:event.startAt,endAt:event.endAt,date:start.date,startTime:start.time,endTime:end.time,allDay:event.allDay,areaCodeId:event.areaCodeId,areaLabel:event.areaCodeId?codes.find(code=>code.id===event.areaCodeId)?.label??null:null,location:event.location,editable:true,sourceUrl:null} satisfies CalendarEvent;}
export async function createCalendarEvent(projectId:string,userId:string,input:unknown){const data=eventSchema.parse(input),id=randomUUID(),timestamp=nowIso();const stored={...data,createdBy:userId,version:1,createdAt:timestamp,updatedAt:timestamp};await projectCollection(projectId,"calendarEvents").doc(id).set(stored);await writeAuditLog(projectId,userId,"CALENDAR_EVENTS_INSERT",null,stored);return {id};}
export async function updateCalendarEvent(projectId:string,id:string,input:unknown){const data=eventSchema.parse(input),ref=projectCollection(projectId,"calendarEvents").doc(id),before=await ref.get();if(!before.exists)return undefined;const update={...data,version:Number(before.data()?.version??1)+1,updatedAt:nowIso()};await ref.update(update);await writeAuditLog(projectId,null,"CALENDAR_EVENTS_UPDATE",before.data()??null,update);return {id};}
