import "server-only";
import { z } from "zod";
import { query } from "@/lib/server/db";

export type CalendarEvent={id:string;source:"schedule"|"progress"|"next_plan"|"issue";title:string;description:string;eventType:string;startAt:string;endAt:string;date:string;startTime:string;endTime:string;allDay:boolean;areaCodeId:string|null;areaLabel:string|null;location:string;editable:boolean;sourceUrl:string|null};
const eventSchema=z.object({title:z.string().trim().min(1).max(200),description:z.string().max(10000),eventType:z.enum(["meeting","milestone","work","other"]),startAt:z.string().datetime(),endAt:z.string().datetime(),allDay:z.boolean(),areaCodeId:z.string().uuid().nullable(),location:z.string().trim().max(200)}).superRefine((d,ctx)=>{if(d.endAt<d.startAt)ctx.addIssue({code:"custom",path:["endAt"],message:"종료일시는 시작일시 이후여야 합니다."});for(const field of ["startAt","endAt"] as const){const date=new Date(d[field]);if(date.getUTCMinutes()%10!==0||date.getUTCSeconds()!==0)ctx.addIssue({code:"custom",path:[field],message:"시간은 10분 단위로 입력해 주세요."});}});

export async function listCalendarEvents(projectId:string,from:string,to:string){
  const r=await query<CalendarEvent>(`select event.id,'schedule'::text source,event.title,event.description,event.event_type as "eventType",event.start_at::text as "startAt",event.end_at::text as "endAt",(event.start_at at time zone project.timezone)::date::text date,to_char(event.start_at at time zone project.timezone,'HH24:MI') as "startTime",to_char(event.end_at at time zone project.timezone,'HH24:MI') as "endTime",event.all_day as "allDay",event.area_code_id as "areaCodeId",area.label as "areaLabel",event.location,true editable,null::text as "sourceUrl"
    from project_tool.calendar_events event join project_tool.projects project on project.id=event.project_id left join project_tool.common_codes area on area.id=event.area_code_id
    where event.project_id=$1 and event.start_at < ($3::date+1) and event.end_at >= $2::date
    union all select progress.id,'progress',progress.task_name,progress.plan_detail,'milestone',progress.plan_target_date::timestamptz::text,progress.plan_target_date::timestamptz::text,progress.plan_target_date::text,'','',true,progress.area_code_id,area.label,'',false,'/weekly-progress?edit='||progress.id
    from project_tool.weekly_progress progress join project_tool.common_codes area on area.id=progress.area_code_id where progress.project_id=$1 and progress.plan_target_date between $2::date and $3::date
    union all select progress.id,'next_plan',progress.task_name,progress.next_plan,'work',progress.next_target_date::timestamptz::text,progress.next_target_date::timestamptz::text,progress.next_target_date::text,'','',true,progress.area_code_id,area.label,'',false,'/weekly-progress?edit='||progress.id
    from project_tool.weekly_progress progress join project_tool.common_codes area on area.id=progress.area_code_id where progress.project_id=$1 and progress.next_target_date between $2::date and $3::date
    union all select item.id,'issue',item.title,item.description,'other',item.created_at::text,item.created_at::text,item.created_at::date::text,to_char(item.created_at,'HH24:MI'),to_char(item.created_at,'HH24:MI'),false,item.track_code_id,track.label,'',false,'/items/'||item.id
    from project_tool.issue_risks item join project_tool.common_codes track on track.id=item.track_code_id where item.project_id=$1 and item.archived_at is null and item.created_at::date between $2::date and $3::date order by "startAt"`,[projectId,from,to]);return r.rows;
}
export async function getCalendarEvent(projectId:string,id:string){const r=await query<CalendarEvent>(`select event.id,'schedule'::text source,event.title,event.description,event.event_type as "eventType",event.start_at::text as "startAt",event.end_at::text as "endAt",(event.start_at at time zone project.timezone)::date::text date,to_char(event.start_at at time zone project.timezone,'HH24:MI') as "startTime",to_char(event.end_at at time zone project.timezone,'HH24:MI') as "endTime",event.all_day as "allDay",event.area_code_id as "areaCodeId",area.label as "areaLabel",event.location,true editable,null::text as "sourceUrl" from project_tool.calendar_events event join project_tool.projects project on project.id=event.project_id left join project_tool.common_codes area on area.id=event.area_code_id where event.project_id=$1 and event.id=$2`,[projectId,id]);return r.rows[0]??null;}
export async function createCalendarEvent(projectId:string,userId:string,input:unknown){const d=eventSchema.parse(input);const r=await query<{id:string}>(`insert into project_tool.calendar_events(project_id,title,description,event_type,start_at,end_at,all_day,area_code_id,location,created_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) returning id`,[projectId,d.title,d.description,d.eventType,d.startAt,d.endAt,d.allDay,d.areaCodeId,d.location,userId]);return r.rows[0];}
export async function updateCalendarEvent(projectId:string,id:string,input:unknown){const d=eventSchema.parse(input);const r=await query<{id:string}>(`update project_tool.calendar_events set title=$1,description=$2,event_type=$3,start_at=$4,end_at=$5,all_day=$6,area_code_id=$7,location=$8 where id=$9 and project_id=$10 returning id`,[d.title,d.description,d.eventType,d.startAt,d.endAt,d.allDay,d.areaCodeId,d.location,id,projectId]);return r.rows[0];}
