import "server-only";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import { getDocument, listDocuments, nowIso, projectCollection, projectRef, writeAuditLog } from "@/lib/server/db";
import { DomainError } from "@/lib/server/items";

export type CommonCodeGroup={id:string;code:string;label:string;description:string|null;sortOrder:number;isActive:boolean;isSystem:boolean;codeCount:number;activeCodeCount:number};
export type CommonCode={id:string;groupId:string;groupCode:string;groupLabel:string;code:string;label:string;sortOrder:number;isActive:boolean;minScore:number|null};
type StoredGroup=Omit<CommonCodeGroup,"codeCount"|"activeCodeCount">;
type StoredCode=Omit<CommonCode,"groupLabel">;
const codePattern=/^[A-Za-z][A-Za-z0-9_-]*$/;
const createGroupSchema=z.object({code:z.string().trim().min(1).max(50).regex(codePattern),label:z.string().trim().min(1).max(100),description:z.string().trim().max(300).nullable().optional(),sortOrder:z.number().int().min(0).max(9999)});
const updateGroupSchema=z.object({label:z.string().trim().min(1).max(100),description:z.string().trim().max(300).nullable().optional(),sortOrder:z.number().int().min(0).max(9999),isActive:z.boolean()});
const createCodeSchema=z.object({groupId:z.string().uuid(),code:z.string().trim().min(1).max(50).regex(codePattern),label:z.string().trim().min(1).max(100),sortOrder:z.number().int().min(0).max(9999),minScore:z.number().int().min(1).max(9).nullable().optional()});
const updateCodeSchema=z.object({label:z.string().trim().min(1).max(100),sortOrder:z.number().int().min(0).max(9999),isActive:z.boolean(),minScore:z.number().int().min(1).max(9).nullable().optional()});

async function assertAdmin(projectId:string,userId:string){const member=await projectRef(projectId).collection("members").doc(userId).get();if(!member.exists||member.data()?.role!=="pmo_admin")throw new DomainError("FORBIDDEN","공통코드 설정 권한이 없습니다.");}
function metadata(groupCode:string,minScore:number|null|undefined){if(groupCode!=="escalation_level")return null;if(minScore==null)throw new DomainError("INVALID_CODE","에스컬레이션 레벨에는 최소 점수가 필요합니다.");return minScore;}

export async function listCommonCodeGroups(projectId:string){const [groups,codes]=await Promise.all([listDocuments<StoredGroup>(projectId,"commonCodeGroups"),listDocuments<StoredCode>(projectId,"commonCodes")]);return groups.map(group=>({...group,codeCount:codes.filter(code=>code.groupId===group.id).length,activeCodeCount:codes.filter(code=>code.groupId===group.id&&code.isActive).length})).sort((a,b)=>a.sortOrder-b.sortOrder||a.label.localeCompare(b.label,"ko"));}
export async function listCommonCodes(projectId:string,includeInactive=true,groupId?:string){const [groups,codes]=await Promise.all([listDocuments<StoredGroup>(projectId,"commonCodeGroups"),listDocuments<StoredCode>(projectId,"commonCodes")]);const groupMap=new Map(groups.map(group=>[group.id,group]));return codes.filter(code=>(!groupId||code.groupId===groupId)&&(includeInactive||(code.isActive&&groupMap.get(code.groupId)?.isActive))).map(code=>({...code,groupLabel:groupMap.get(code.groupId)?.label??code.groupCode})).sort((a,b)=>(groupMap.get(a.groupId)?.sortOrder??0)-(groupMap.get(b.groupId)?.sortOrder??0)||a.sortOrder-b.sortOrder||a.label.localeCompare(b.label,"ko"));}
export async function getCodeOptions(projectId:string){const codes=await listCommonCodes(projectId,false);return {categories:codes.filter(code=>code.groupCode==="category"),tracks:codes.filter(code=>code.groupCode==="track"),escalations:codes.filter(code=>code.groupCode==="escalation_level")};}

export async function createCommonCodeGroup(projectId:string,userId:string,input:unknown){const data=createGroupSchema.parse(input),requestId=randomUUID();await assertAdmin(projectId,userId);const groups=await listDocuments<StoredGroup>(projectId,"commonCodeGroups");if(groups.some(group=>group.code.toLowerCase()===data.code.toLowerCase()))throw new DomainError("DUPLICATE_CODE","동일한 그룹 코드가 이미 존재합니다.");const id=randomUUID(),timestamp=nowIso(),stored={code:data.code,label:data.label,description:data.description||null,sortOrder:data.sortOrder,isActive:true,isSystem:false,createdAt:timestamp,updatedAt:timestamp};await projectCollection(projectId,"commonCodeGroups").doc(id).set(stored);await writeAuditLog(projectId,userId,"GROUP_INSERT",null,stored);return {group:{id,...stored,codeCount:0,activeCodeCount:0},requestId};}
export async function updateCommonCodeGroup(projectId:string,userId:string,groupId:string,input:unknown){const data=updateGroupSchema.parse(input),requestId=randomUUID();await assertAdmin(projectId,userId);const current=await getDocument<StoredGroup>(projectId,"commonCodeGroups",groupId);if(!current)throw new DomainError("NOT_FOUND","코드 그룹을 찾을 수 없습니다.");if(current.isSystem&&!data.isActive)throw new DomainError("INVALID_CODE","시스템 코드 그룹은 비활성화할 수 없습니다.");const update={label:data.label,description:data.description||null,sortOrder:data.sortOrder,isActive:data.isActive,updatedAt:nowIso()};await projectCollection(projectId,"commonCodeGroups").doc(groupId).update(update);await writeAuditLog(projectId,userId,"GROUP_UPDATE",current,update);const group=(await listCommonCodeGroups(projectId)).find(row=>row.id===groupId)!;return {group,requestId};}
export async function createCommonCode(projectId:string,userId:string,input:unknown){const data=createCodeSchema.parse(input),requestId=randomUUID();await assertAdmin(projectId,userId);const group=await getDocument<StoredGroup>(projectId,"commonCodeGroups",data.groupId);if(!group)throw new DomainError("NOT_FOUND","코드 그룹을 찾을 수 없습니다.");const codes=await listDocuments<StoredCode>(projectId,"commonCodes"),minScore=metadata(group.code,data.minScore);if(codes.some(code=>code.groupId===data.groupId&&(code.code.toLowerCase()===data.code.toLowerCase()||(minScore!==null&&code.minScore===minScore))))throw new DomainError("DUPLICATE_CODE","그룹 내 동일한 코드 또는 최소 점수가 이미 존재합니다.");const id=randomUUID(),timestamp=nowIso(),stored={groupId:data.groupId,groupCode:group.code,code:data.code,label:data.label,sortOrder:data.sortOrder,isActive:true,minScore,createdAt:timestamp,updatedAt:timestamp};await projectCollection(projectId,"commonCodes").doc(id).set(stored);await writeAuditLog(projectId,userId,"COMMON_CODE_INSERT",null,stored);return {code:{id,...stored,groupLabel:group.label},requestId};}
export async function updateCommonCode(projectId:string,userId:string,codeId:string,input:unknown){const data=updateCodeSchema.parse(input),requestId=randomUUID();await assertAdmin(projectId,userId);const current=await getDocument<StoredCode>(projectId,"commonCodes",codeId);if(!current)throw new DomainError("NOT_FOUND","공통코드를 찾을 수 없습니다.");const codes=await listDocuments<StoredCode>(projectId,"commonCodes");if(current.isActive&&!data.isActive&&codes.filter(code=>code.groupId===current.groupId&&code.isActive&&code.id!==codeId).length===0)throw new DomainError("LAST_ACTIVE_CODE","그룹에는 하나 이상의 활성 코드가 필요합니다.");const minScore=metadata(current.groupCode,data.minScore);if(minScore!==null&&codes.some(code=>code.id!==codeId&&code.groupId===current.groupId&&code.minScore===minScore))throw new DomainError("DUPLICATE_CODE","동일한 최소 점수가 이미 존재합니다.");const update={label:data.label,sortOrder:data.sortOrder,isActive:data.isActive,minScore,updatedAt:nowIso()};await projectCollection(projectId,"commonCodes").doc(codeId).update(update);await writeAuditLog(projectId,userId,"COMMON_CODE_UPDATE",current,update);const group=await getDocument<StoredGroup>(projectId,"commonCodeGroups",current.groupId);return {code:{...current,...update,groupLabel:group?.label??current.groupCode},requestId};}
