import "server-only";

import { randomUUID } from "node:crypto";
import { z } from "zod";
import { riskScore } from "@/lib/domain/items";
import { businessDaysSince, getDb, getDocument, listDocuments, nowIso, projectCollection, projectRef, writeAuditLog } from "@/lib/server/db";

const kindSchema=z.enum(["issue","risk"]),probabilitySchema=z.enum(["low","medium","high"]),statusSchema=z.enum(["registered","in_progress","resolved","on_hold"]);
export const createItemSchema=z.object({kind:kindSchema,categoryCodeId:z.string().uuid(),trackCodeId:z.string().uuid(),title:z.string().trim().min(1).max(200),description:z.string().trim().max(10000).default(""),probability:probabilitySchema,impact:probabilitySchema,exposureText:z.string().trim().max(500).optional(),ownerText:z.string().trim().max(100).optional(),escalationCodeId:z.string().uuid().optional()});
export const updateItemSchema=createItemSchema.omit({kind:true,escalationCodeId:true}).extend({version:z.number().int().positive()});
export const statusUpdateSchema=z.object({status:statusSchema,version:z.number().int().positive()});
export const escalationUpdateSchema=z.object({escalationCodeId:z.string().uuid(),version:z.number().int().positive()});
export const commentSchema=z.object({body:z.string().trim().min(1).max(5000),version:z.number().int().positive()});
export const archiveSchema=z.object({version:z.number().int().positive()});

export class DomainError extends Error{constructor(public code:"FORBIDDEN"|"NOT_FOUND"|"VERSION_CONFLICT"|"DUPLICATE_CODE"|"LAST_ACTIVE_CODE"|"INVALID_CODE",message:string){super(message);}}
export type ItemRow={id:string;displayId:string;projectId:string;trackCodeId:string;kind:"issue"|"risk";categoryCodeId:string;categoryCode:string;categoryLabel:string;title:string;description:string;probability:"low"|"medium"|"high";impact:"low"|"medium"|"high";exposureText:string|null;ownerText:string|null;escalationCodeId:string;escalationCode:string;escalationLabel:string;status:"registered"|"in_progress"|"resolved"|"on_hold";trackName:string;trackCode:string;ownerName:string|null;createdAt:string;updatedAt:string;resolvedAt:string|null;businessDaysIdle:number;isStale:boolean;version:number};
export type ItemEventRow={id:string;eventType:"created"|"comment"|"status_changed"|"level_changed"|"edited"|"archived";actorName:string;body:string|null;beforeData:Record<string,unknown>|null;afterData:Record<string,unknown>|null;createdAt:string};
export type ItemFilters={q?:string;kind?:string;status?:string;category?:string;probability?:string;impact?:string;open?:boolean;stale?:boolean;page?:number;pageSize?:number};
type StoredItem={id:string;displayId:string;projectId:string;trackCodeId:string;kind:"issue"|"risk";categoryCodeId:string;title:string;description:string;probability:"low"|"medium"|"high";impact:"low"|"medium"|"high";exposureText:string|null;ownerText:string|null;ownerUserId:string|null;escalationCodeId:string;status:"registered"|"in_progress"|"resolved"|"on_hold";createdBy:string;version:number;createdAt:string;updatedAt:string;resolvedAt:string|null;archivedAt:string|null};
type StoredCode={id:string;groupId:string;groupCode:string;code:string;label:string;sortOrder:number;isActive:boolean;minScore:number|null};
type StoredEvent=ItemEventRow&{itemId:string;actorId:string};

async function projectConfig(projectId:string){const snapshot=await projectRef(projectId).get();return {staleBusinessDays:Number(snapshot.data()?.staleBusinessDays??3)};}
async function enrich(projectId:string,items:StoredItem[]){const [codes,config]=await Promise.all([listDocuments<StoredCode>(projectId,"commonCodes"),projectConfig(projectId)]),codeMap=new Map(codes.map(code=>[code.id,code]));return items.map(item=>{const category=codeMap.get(item.categoryCodeId),track=codeMap.get(item.trackCodeId),escalation=codeMap.get(item.escalationCodeId),idle=businessDaysSince(item.updatedAt);return {id:item.id,displayId:item.displayId,projectId:item.projectId,trackCodeId:item.trackCodeId,kind:item.kind,categoryCodeId:item.categoryCodeId,categoryCode:category?.code??"",categoryLabel:category?.label??"-",title:item.title,description:item.description,probability:item.kind==="issue"?"high":item.probability,impact:item.impact,exposureText:item.exposureText,ownerText:item.ownerText,escalationCodeId:item.escalationCodeId,escalationCode:escalation?.code??"",escalationLabel:escalation?.label??"-",status:item.status,trackName:track?.label??"-",trackCode:track?.code??"",ownerName:item.ownerText,createdAt:item.createdAt,updatedAt:item.updatedAt,resolvedAt:item.resolvedAt,businessDaysIdle:idle,isStale:["registered","in_progress"].includes(item.status)&&idle>=config.staleBusinessDays,version:item.version} satisfies ItemRow;});}
function filterItems(items:ItemRow[],filters:ItemFilters){const query=filters.q?.trim().toLocaleLowerCase("ko");return items.filter(item=>(!filters.kind||!kindSchema.options.includes(filters.kind as never)||item.kind===filters.kind)&&(!filters.status||!statusSchema.options.includes(filters.status as never)||item.status===filters.status)&&(!filters.category?.trim()||item.categoryCode===filters.category.trim())&&(!filters.probability||!probabilitySchema.options.includes(filters.probability as never)||item.probability===filters.probability)&&(!filters.impact||!probabilitySchema.options.includes(filters.impact as never)||item.impact===filters.impact)&&(!filters.open||["registered","in_progress"].includes(item.status))&&(!filters.stale||item.isStale)&&(!query||`${item.title} ${item.description} ${item.ownerName??""}`.toLocaleLowerCase("ko").includes(query)));}

export async function listTracks(projectId:string){const codes=await listDocuments<StoredCode>(projectId,"commonCodes");return codes.filter(code=>code.groupCode==="track"&&code.isActive).sort((a,b)=>a.sortOrder-b.sortOrder||a.label.localeCompare(b.label,"ko")).map(code=>({id:code.id,name:code.label}));}
export async function listItems(projectId:string,filters:ItemFilters={}){const stored=(await listDocuments<StoredItem>(projectId,"items")).filter(item=>!item.archivedAt),items=filterItems(await enrich(projectId,stored),filters).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)),pageSize=Math.min(100,Math.max(10,filters.pageSize??30)),total=items.length,totalPages=Math.max(1,Math.ceil(total/pageSize)),page=Math.min(Math.max(1,filters.page??1),totalPages);return {items:items.slice((page-1)*pageSize,page*pageSize),total,page,pageSize,totalPages};}
export async function listItemsForExport(projectId:string,filters:ItemFilters={}){const stored=(await listDocuments<StoredItem>(projectId,"items")).filter(item=>!item.archivedAt);return filterItems(await enrich(projectId,stored),filters).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,10000);}
export async function getItemDetail(projectId:string,itemId:string){const item=await getDocument<StoredItem>(projectId,"items",itemId);if(!item||item.archivedAt)return null;const [enriched,events]=await Promise.all([enrich(projectId,[item]),listDocuments<StoredEvent>(projectId,"itemEvents")]);return {item:enriched[0],events:events.filter(event=>event.itemId===itemId).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(({itemId:_itemId,actorId:_actorId,...event})=>event)};}
export async function getDashboard(projectId:string){const all=(await listDocuments<StoredItem>(projectId,"items")).filter(item=>!item.archivedAt),items=await enrich(projectId,all),open=items.filter(item=>["registered","in_progress"].includes(item.status)),codes=await listDocuments<StoredCode>(projectId,"commonCodes"),categories=codes.filter(code=>code.groupCode==="category"&&code.isActive).sort((a,b)=>a.sortOrder-b.sortOrder).map(code=>({category:code.code,label:code.label,count:open.filter(item=>item.categoryCodeId===code.id).length})),matrix=Array.from(open.reduce((map,item)=>{const key=`${item.probability}:${item.impact}`,current=map.get(key)??{probability:item.probability,impact:item.impact,count:0};current.count+=1;map.set(key,current);return map;},new Map<string,{probability:string;impact:string;count:number}>()).values());return {summary:{total:items.length,openIssues:open.filter(item=>item.kind==="issue").length,openRisks:open.filter(item=>item.kind==="risk").length,stale:open.filter(item=>item.isStale).length},matrix,categories,staleItems:open.filter(item=>item.isStale).sort((a,b)=>a.updatedAt.localeCompare(b.updatedAt)).slice(0,8)};}

async function assertWritePermission(projectId:string,userId:string,itemId?:string,requirePm=false){const [member,item]=await Promise.all([projectRef(projectId).collection("members").doc(userId).get(),itemId?getDocument<StoredItem>(projectId,"items",itemId):Promise.resolve(null)]),role=member.data()?.role,isManager=["pm","pmo_admin"].includes(role),owns=item?item.createdBy===userId||item.ownerUserId===userId:false;if(!member.exists||(requirePm?!isManager:!(isManager||(role==="member"&&(!itemId||owns)))))throw new DomainError("FORBIDDEN","이 작업을 수행할 권한이 없습니다.");}
async function assertCommonCode(projectId:string,codeId:string,groupCode:string){const code=await getDocument<StoredCode>(projectId,"commonCodes",codeId);if(!code||code.groupCode!==groupCode||!code.isActive)throw new DomainError("INVALID_CODE","선택한 공통코드를 사용할 수 없습니다.");return code;}
async function suggestedEscalationId(projectId:string,kind:"issue"|"risk",probability:"low"|"medium"|"high",impact:"low"|"medium"|"high"){const score=riskScore(kind,probability,impact),codes=await listDocuments<StoredCode>(projectId,"commonCodes"),match=codes.filter(code=>code.groupCode==="escalation_level"&&code.isActive&&(code.minScore??1)<=score).sort((a,b)=>(b.minScore??1)-(a.minScore??1)||b.sortOrder-a.sortOrder)[0];if(!match)throw new DomainError("INVALID_CODE","적용 가능한 에스컬레이션 공통코드가 없습니다.");return match.id;}
function mutationError(item:StoredItem|null,version:number){if(!item||item.archivedAt)throw new DomainError("NOT_FOUND","항목을 찾을 수 없습니다.");if(item.version!==version)throw new DomainError("VERSION_CONFLICT","다른 사용자가 먼저 수정했습니다. 최신 내용을 다시 확인해 주세요.");}
function asRecord(value:unknown){return value as Record<string,unknown>;}

export async function createItem(projectId:string,userId:string,input:unknown){const data=createItemSchema.parse(input),probability=data.kind==="issue"?"high":data.probability,requestId=randomUUID();await assertWritePermission(projectId,userId);await Promise.all([assertCommonCode(projectId,data.categoryCodeId,"category"),assertCommonCode(projectId,data.trackCodeId,"track")]);const escalationCodeId=data.escalationCodeId??await suggestedEscalationId(projectId,data.kind,probability,data.impact);await assertCommonCode(projectId,escalationCodeId,"escalation_level");const id=randomUUID(),timestamp=nowIso(),itemRef=projectCollection(projectId,"items").doc(id),eventRef=projectCollection(projectId,"itemEvents").doc(randomUUID()),counterRef=projectCollection(projectId,"meta").doc("itemSequence");let displayId="";await getDb().runTransaction(async tx=>{const counter=await tx.get(counterRef),next=Number(counter.data()?.value??0)+1;displayId=`IR-${new Date().getUTCFullYear()}-${String(next).padStart(6,"0")}`;tx.set(counterRef,{value:next});tx.set(itemRef,{displayId,projectId,trackCodeId:data.trackCodeId,kind:data.kind,categoryCodeId:data.categoryCodeId,title:data.title,description:data.description,probability,impact:data.impact,exposureText:data.exposureText||null,ownerText:data.ownerText||null,ownerUserId:null,escalationCodeId,status:"registered",createdBy:userId,version:1,createdAt:timestamp,updatedAt:timestamp,resolvedAt:null,archivedAt:null});tx.set(eventRef,{itemId:id,eventType:"created",actorId:userId,actorName:"PMO 관리자",body:"신규 등록",beforeData:null,afterData:null,createdAt:timestamp});});await writeAuditLog(projectId,userId,"ITEM_INSERT",null,{id,displayId,title:data.title});return {id,displayId,requestId};}
export async function updateItem(projectId:string,userId:string,itemId:string,input:unknown){const data=updateItemSchema.parse(input),requestId=randomUUID();await assertWritePermission(projectId,userId,itemId);await Promise.all([assertCommonCode(projectId,data.categoryCodeId,"category"),assertCommonCode(projectId,data.trackCodeId,"track")]);const ref=projectCollection(projectId,"items").doc(itemId),eventRef=projectCollection(projectId,"itemEvents").doc(randomUUID());let before:StoredItem|null=null,version=0;await getDb().runTransaction(async tx=>{const snapshot=await tx.get(ref);before=snapshot.exists?({id:snapshot.id,...snapshot.data()} as StoredItem):null;mutationError(before,data.version);version=data.version+1;const update={trackCodeId:data.trackCodeId,categoryCodeId:data.categoryCodeId,title:data.title,description:data.description,probability:before!.kind==="issue"?"high":data.probability,impact:data.impact,exposureText:data.exposureText||null,ownerText:data.ownerText||null,version,updatedAt:nowIso()};tx.update(ref,update);tx.set(eventRef,{itemId,eventType:"edited",actorId:userId,actorName:"PMO 관리자",body:"기본 정보 수정",beforeData:before,afterData:update,createdAt:nowIso()});});await writeAuditLog(projectId,userId,"ITEM_UPDATE",asRecord(before),{version});return {version,requestId};}
export async function updateStatus(projectId:string,userId:string,itemId:string,input:unknown){const data=statusUpdateSchema.parse(input);return updateSingleField(projectId,userId,itemId,data.version,data.status);}
async function updateSingleField(projectId:string,userId:string,itemId:string,expectedVersion:number,status:"registered"|"in_progress"|"resolved"|"on_hold"){const requestId=randomUUID();await assertWritePermission(projectId,userId,itemId);const ref=projectCollection(projectId,"items").doc(itemId),eventRef=projectCollection(projectId,"itemEvents").doc(randomUUID());let before:StoredItem|null=null,version=0;await getDb().runTransaction(async tx=>{const snapshot=await tx.get(ref);before=snapshot.exists?({id:snapshot.id,...snapshot.data()} as StoredItem):null;mutationError(before,expectedVersion);version=expectedVersion+1;const update={status,version,updatedAt:nowIso(),resolvedAt:status==="resolved"?nowIso():null};tx.update(ref,update);tx.set(eventRef,{itemId,eventType:"status_changed",actorId:userId,actorName:"PMO 관리자",body:"상태 변경",beforeData:{value:before!.status},afterData:{value:status},createdAt:nowIso()});});await writeAuditLog(projectId,userId,"ITEM_UPDATE",asRecord(before),{status,version});return {version,requestId};}
export async function updateEscalation(projectId:string,userId:string,itemId:string,input:unknown){const data=escalationUpdateSchema.parse(input),requestId=randomUUID();await assertWritePermission(projectId,userId,itemId,true);const nextCode=await assertCommonCode(projectId,data.escalationCodeId,"escalation_level"),ref=projectCollection(projectId,"items").doc(itemId),eventRef=projectCollection(projectId,"itemEvents").doc(randomUUID());let before:StoredItem|null=null,version=0;await getDb().runTransaction(async tx=>{const snapshot=await tx.get(ref);before=snapshot.exists?({id:snapshot.id,...snapshot.data()} as StoredItem):null;mutationError(before,data.version);const currentCode=await tx.get(projectCollection(projectId,"commonCodes").doc(before!.escalationCodeId));version=data.version+1;const update={escalationCodeId:data.escalationCodeId,version,updatedAt:nowIso()};tx.update(ref,update);tx.set(eventRef,{itemId,eventType:"level_changed",actorId:userId,actorName:"PMO 관리자",body:"에스컬레이션 레벨 변경",beforeData:{value:currentCode.data()?.label??"-"},afterData:{value:nextCode.label},createdAt:nowIso()});});await writeAuditLog(projectId,userId,"ITEM_UPDATE",asRecord(before),{escalationCodeId:data.escalationCodeId,version});return {version,requestId};}
export async function addComment(projectId:string,userId:string,itemId:string,input:unknown){const data=commentSchema.parse(input),requestId=randomUUID();await assertWritePermission(projectId,userId,itemId);const ref=projectCollection(projectId,"items").doc(itemId),eventRef=projectCollection(projectId,"itemEvents").doc(randomUUID());let version=0;await getDb().runTransaction(async tx=>{const snapshot=await tx.get(ref),item=snapshot.exists?({id:snapshot.id,...snapshot.data()} as StoredItem):null;mutationError(item,data.version);version=data.version+1;tx.update(ref,{version,updatedAt:nowIso()});tx.set(eventRef,{itemId,eventType:"comment",actorId:userId,actorName:"PMO 관리자",body:data.body,beforeData:null,afterData:null,createdAt:nowIso()});});return {version,requestId};}
export async function archiveItem(projectId:string,userId:string,itemId:string,input:unknown){const data=archiveSchema.parse(input),requestId=randomUUID();await assertWritePermission(projectId,userId,itemId,true);const ref=projectCollection(projectId,"items").doc(itemId),eventRef=projectCollection(projectId,"itemEvents").doc(randomUUID());let before:StoredItem|null=null,version=0;await getDb().runTransaction(async tx=>{const snapshot=await tx.get(ref);before=snapshot.exists?({id:snapshot.id,...snapshot.data()} as StoredItem):null;mutationError(before,data.version);version=data.version+1;const update={archivedAt:nowIso(),updatedAt:nowIso(),version};tx.update(ref,update);tx.set(eventRef,{itemId,eventType:"archived",actorId:userId,actorName:"PMO 관리자",body:"항목 보관",beforeData:null,afterData:null,createdAt:nowIso()});});await writeAuditLog(projectId,userId,"ITEM_UPDATE",asRecord(before),{archivedAt:nowIso(),version});return {version,requestId};}
