import "server-only";
import { z } from "zod";
import { ensureFirestoreSeeded, getDb, nowIso, projectRef, writeAuditLog } from "@/lib/server/db";

export type ProjectInformation={id:string;code:string;name:string;openMethod:"phased"|"big_bang";startDate:string|null;endDate:string|null;firstOpenDate:string|null;secondOpenDate:string|null;goLiveDate:string|null;durationMonths:number;durationDays:number;customerName:string;vendorName:string;customerPm:string;customerPmoCount:number;vendorPm:string;vendorPmoCount:number;projectGrade:"A"|"B"|"C";timezone:string;staleBusinessDays:number};
const schema=z.object({name:z.string().trim().min(1).max(150),openMethod:z.enum(["phased","big_bang"]),startDate:z.string().date(),endDate:z.string().date(),firstOpenDate:z.string().date().nullable(),secondOpenDate:z.string().date().nullable(),goLiveDate:z.string().date().nullable(),customerName:z.string().trim().min(1).max(150),vendorName:z.string().trim().min(1).max(150),customerPm:z.string().trim().min(1).max(100),customerPmoCount:z.number().int().min(0).max(999),vendorPm:z.string().trim().min(1).max(100),vendorPmoCount:z.number().int().min(0).max(999),projectGrade:z.enum(["A","B","C"]),timezone:z.string().trim().min(1).max(50),staleBusinessDays:z.number().int().min(1).max(30)}).superRefine((d,ctx)=>{if(d.endDate<d.startDate)ctx.addIssue({code:"custom",path:["endDate"],message:"종료일은 시작일 이후여야 합니다."});const inPeriod=(date:string|null)=>date!==null&&date>=d.startDate&&date<=d.endDate;if(d.openMethod==="phased"){if(!d.firstOpenDate)ctx.addIssue({code:"custom",path:["firstOpenDate"],message:"1차 오픈일을 입력해 주세요."});else if(!inPeriod(d.firstOpenDate))ctx.addIssue({code:"custom",path:["firstOpenDate"],message:"1차 오픈일은 프로젝트 기간 내여야 합니다."});if(!d.secondOpenDate)ctx.addIssue({code:"custom",path:["secondOpenDate"],message:"2차 오픈일을 입력해 주세요."});else if(!inPeriod(d.secondOpenDate)||Boolean(d.firstOpenDate&&d.secondOpenDate<d.firstOpenDate))ctx.addIssue({code:"custom",path:["secondOpenDate"],message:"2차 오픈일은 1차 오픈 이후 프로젝트 기간 내여야 합니다."});}else if(!d.goLiveDate)ctx.addIssue({code:"custom",path:["goLiveDate"],message:"오픈일을 입력해 주세요."});else if(!inPeriod(d.goLiveDate))ctx.addIssue({code:"custom",path:["goLiveDate"],message:"오픈일은 프로젝트 기간 내여야 합니다."});});

function duration(startDate:string|null,endDate:string|null){if(!startDate||!endDate)return {durationMonths:0,durationDays:0};const start=new Date(`${startDate}T00:00:00Z`),end=new Date(`${endDate}T00:00:00Z`);let months=(end.getUTCFullYear()-start.getUTCFullYear())*12+end.getUTCMonth()-start.getUTCMonth();const anchor=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+months,start.getUTCDate()));if(anchor>end){months-=1;anchor.setUTCMonth(anchor.getUTCMonth()-1);}return {durationMonths:months,durationDays:Math.max(0,Math.round((end.getTime()-anchor.getTime())/86_400_000))};}
function mapProject(id:string,data:Record<string,unknown>):ProjectInformation{const startDate=(data.startDate as string|null)??null,endDate=(data.endDate as string|null)??null;return {id,code:String(data.code??""),name:String(data.name??""),openMethod:(data.openMethod as ProjectInformation["openMethod"])??"phased",startDate,endDate,firstOpenDate:(data.firstOpenDate as string|null)??null,secondOpenDate:(data.secondOpenDate as string|null)??null,goLiveDate:(data.goLiveDate as string|null)??null,...duration(startDate,endDate),customerName:String(data.customerName??""),vendorName:String(data.vendorName??""),customerPm:String(data.customerPm??""),customerPmoCount:Number(data.customerPmoCount??0),vendorPm:String(data.vendorPm??""),vendorPmoCount:Number(data.vendorPmoCount??0),projectGrade:(data.projectGrade as ProjectInformation["projectGrade"])??"B",timezone:String(data.timezone??"Asia/Seoul"),staleBusinessDays:Number(data.staleBusinessDays??3)};}

export async function getProjectInformation(projectId:string):Promise<ProjectInformation>{await ensureFirestoreSeeded(projectId);const snapshot=await projectRef(projectId).get();if(!snapshot.exists)throw new Error("Project not found.");return mapProject(snapshot.id,snapshot.data()??{});}
export async function updateProjectInformation(projectId:string,input:unknown){const data=schema.parse(input);await ensureFirestoreSeeded(projectId);const ref=projectRef(projectId);const before=await ref.get();const update={...data,firstOpenDate:data.openMethod==="phased"?data.firstOpenDate:null,secondOpenDate:data.openMethod==="phased"?data.secondOpenDate:null,goLiveDate:data.openMethod==="big_bang"?data.goLiveDate:null,updatedAt:nowIso()};await getDb().runTransaction(async tx=>{if(!before.exists)throw new Error("Project not found");tx.update(ref,update);});await writeAuditLog(projectId,null,"PROJECT_UPDATE",before.data()??null,update);return getProjectInformation(projectId);}
