import "server-only";
import { z } from "zod";
import { query } from "@/lib/server/db";

export type ProjectInformation={id:string;code:string;name:string;openMethod:"phased"|"big_bang";startDate:string|null;endDate:string|null;firstOpenDate:string|null;secondOpenDate:string|null;goLiveDate:string|null;durationMonths:number;durationDays:number;customerName:string;vendorName:string;customerPm:string;customerPmoCount:number;vendorPm:string;vendorPmoCount:number;projectGrade:"A"|"B"|"C";timezone:string;staleBusinessDays:number};
const schema=z.object({name:z.string().trim().min(1).max(150),openMethod:z.enum(["phased","big_bang"]),startDate:z.string().date(),endDate:z.string().date(),firstOpenDate:z.string().date().nullable(),secondOpenDate:z.string().date().nullable(),goLiveDate:z.string().date().nullable(),customerName:z.string().trim().min(1).max(150),vendorName:z.string().trim().min(1).max(150),customerPm:z.string().trim().min(1).max(100),customerPmoCount:z.number().int().min(0).max(999),vendorPm:z.string().trim().min(1).max(100),vendorPmoCount:z.number().int().min(0).max(999),projectGrade:z.enum(["A","B","C"]),timezone:z.string().trim().min(1).max(50),staleBusinessDays:z.number().int().min(1).max(30)}).superRefine((d,ctx)=>{if(d.endDate<d.startDate)ctx.addIssue({code:"custom",path:["endDate"],message:"종료일은 시작일 이후여야 합니다."});const inPeriod=(date:string|null)=>date!==null&&date>=d.startDate&&date<=d.endDate;if(d.openMethod==="phased"){if(!d.firstOpenDate)ctx.addIssue({code:"custom",path:["firstOpenDate"],message:"1차 오픈일을 입력해 주세요."});else if(!inPeriod(d.firstOpenDate))ctx.addIssue({code:"custom",path:["firstOpenDate"],message:"1차 오픈일은 프로젝트 기간 내여야 합니다."});if(!d.secondOpenDate)ctx.addIssue({code:"custom",path:["secondOpenDate"],message:"2차 오픈일을 입력해 주세요."});else if(!inPeriod(d.secondOpenDate)||Boolean(d.firstOpenDate&&d.secondOpenDate<d.firstOpenDate))ctx.addIssue({code:"custom",path:["secondOpenDate"],message:"2차 오픈일은 1차 오픈 이후 프로젝트 기간 내여야 합니다."});}else if(!d.goLiveDate)ctx.addIssue({code:"custom",path:["goLiveDate"],message:"오픈일을 입력해 주세요."});else if(!inPeriod(d.goLiveDate))ctx.addIssue({code:"custom",path:["goLiveDate"],message:"오픈일은 프로젝트 기간 내여야 합니다."});});
const select=`select id,code,name,open_method as "openMethod",start_date::text as "startDate",end_date::text as "endDate",first_open_date::text as "firstOpenDate",second_open_date::text as "secondOpenDate",go_live_date::text as "goLiveDate",coalesce((extract(year from age(end_date,start_date))*12+extract(month from age(end_date,start_date)))::int,0) as "durationMonths",coalesce(extract(day from age(end_date,start_date))::int,0) as "durationDays",customer_name as "customerName",vendor_name as "vendorName",customer_pm as "customerPm",customer_pmo_count as "customerPmoCount",vendor_pm as "vendorPm",vendor_pmo_count as "vendorPmoCount",project_grade as "projectGrade",timezone,stale_business_days as "staleBusinessDays" from project_tool.projects`;
export async function getProjectInformation(projectId:string){const r=await query<ProjectInformation>(`${select} where id=$1`,[projectId]);return r.rows[0];}
export async function updateProjectInformation(projectId:string,input:unknown){const d=schema.parse(input);const r=await query<ProjectInformation>(`update project_tool.projects set name=$1,open_method=$2,start_date=$3,end_date=$4,first_open_date=$5,second_open_date=$6,go_live_date=$7,customer_name=$8,vendor_name=$9,customer_pm=$10,customer_pmo_count=$11,vendor_pm=$12,vendor_pmo_count=$13,project_grade=$14,timezone=$15,stale_business_days=$16,updated_at=now() where id=$17 returning id`,[d.name,d.openMethod,d.startDate,d.endDate,d.openMethod==="phased"?d.firstOpenDate:null,d.openMethod==="phased"?d.secondOpenDate:null,d.openMethod==="big_bang"?d.goLiveDate:null,d.customerName,d.vendorName,d.customerPm,d.customerPmoCount,d.vendorPm,d.vendorPmoCount,d.projectGrade,d.timezone,d.staleBusinessDays,projectId]);return getProjectInformation(r.rows[0].id);}
