import "server-only";
import { randomUUID } from "node:crypto";
import { z } from "zod";
import type { CommonCode } from "@/lib/server/common-codes";
import { getCodeOptions } from "@/lib/server/common-codes";
import { getDocument, listDocuments, nowIso, projectCollection, writeAuditLog } from "@/lib/server/db";
import { DomainError } from "@/lib/server/items";

export type ProjectWeek={id:string;weekKey:string;label:string;startDate:string;endDate:string;status:"open"|"closed"};
export type WeeklyReport={id:string;weekId:string;weekLabel:string;areaCodeId:string;areaLabel:string;achievements:string;nextPlan:string;issues:string;decisions:string;notes:string;version:number};
export type ProgressRow={id:string;weekId:string;weekLabel:string;areaCodeId:string;areaLabel:string;taskName:string;planDetail:string;planTargetDate:string|null;actualDetail:string;actualDate:string|null;progress:number;nextPlan:string;nextTargetDate:string|null;notes:string;version:number;delayed:boolean};
export type StaffChange={id:string;weekId:string;weekLabel:string;areaCodeId:string;areaLabel:string;changeType:"join"|"leave";currentCount:number;nextCount:number;notes:string;version:number};
export type ActivityLog={id:string;action:string;actorName:string|null;createdAt:string;beforeData:Record<string,unknown>|null;afterData:Record<string,unknown>|null};
type StoredWeek=ProjectWeek&{createdAt:string;updatedAt:string};
type StoredReport=Omit<WeeklyReport,"weekLabel"|"areaLabel">&{createdBy:string;createdAt:string;updatedAt:string};
type StoredProgress=Omit<ProgressRow,"weekLabel"|"areaLabel"|"delayed">&{createdBy:string;createdAt:string;updatedAt:string};
type StoredStaff=Omit<StaffChange,"weekLabel"|"areaLabel">&{createdBy:string;createdAt:string;updatedAt:string};

export async function listProjectWeeks(projectId:string){return (await listDocuments<StoredWeek>(projectId,"weeks")).map(({createdAt:_createdAt,updatedAt:_updatedAt,...week})=>week).sort((a,b)=>b.startDate.localeCompare(a.startDate));}
export async function getWorkOptions(projectId:string){const [weeks,codes]=await Promise.all([listProjectWeeks(projectId),getCodeOptions(projectId)]);return {weeks,areas:codes.tracks as CommonCode[]};}
const weekSchema=z.object({weekKey:z.string().trim().min(7).max(10),label:z.string().trim().min(1).max(50),startDate:z.string().date(),endDate:z.string().date()}).superRefine((d,ctx)=>{if(d.endDate<d.startDate)ctx.addIssue({code:"custom",path:["endDate"],message:"종료일은 시작일 이후여야 합니다."});});
export async function createProjectWeek(projectId:string,input:unknown){const data=weekSchema.parse(input),weeks=await listDocuments<StoredWeek>(projectId,"weeks");if(weeks.some(week=>week.weekKey===data.weekKey))throw new DomainError("DUPLICATE_CODE","동일한 주차 코드가 이미 존재합니다.");const id=randomUUID(),timestamp=nowIso(),stored={...data,status:"open" as const,createdAt:timestamp,updatedAt:timestamp};await projectCollection(projectId,"weeks").doc(id).set(stored);await writeAuditLog(projectId,null,"PROJECT_WEEKS_INSERT",null,stored);return {id,...data,status:"open" as const};}
export async function updateProjectWeekStatus(projectId:string,id:string,status:unknown){const value=z.enum(["open","closed"]).parse(status),current=await getDocument<StoredWeek>(projectId,"weeks",id);if(!current)throw new DomainError("NOT_FOUND","프로젝트 주차를 찾을 수 없습니다.");const update={status:value,updatedAt:nowIso()};await projectCollection(projectId,"weeks").doc(id).update(update);await writeAuditLog(projectId,null,"PROJECT_WEEKS_UPDATE",current,update);return {id,weekKey:current.weekKey,label:current.label,startDate:current.startDate,endDate:current.endDate,status:value};}
export async function listActivityLogs(projectId:string){return (await listDocuments<ActivityLog>(projectId,"auditLogs")).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,200);}

function lookupMaps(weeks:ProjectWeek[],areas:CommonCode[]){return {week:new Map(weeks.map(row=>[row.id,row])),area:new Map(areas.map(row=>[row.id,row]))};}
export async function listWeeklyReports(projectId:string,weekId?:string){const [records,weeks,options]=await Promise.all([listDocuments<StoredReport>(projectId,"weeklyReports"),listProjectWeeks(projectId),getCodeOptions(projectId)]),maps=lookupMaps(weeks,options.tracks);return records.filter(row=>!weekId||row.weekId===weekId).map(row=>({id:row.id,weekId:row.weekId,weekLabel:maps.week.get(row.weekId)?.label??"-",areaCodeId:row.areaCodeId,areaLabel:maps.area.get(row.areaCodeId)?.label??"-",achievements:row.achievements,nextPlan:row.nextPlan,issues:row.issues,decisions:row.decisions,notes:row.notes,version:row.version})).sort((a,b)=>(maps.week.get(b.weekId)?.startDate??"").localeCompare(maps.week.get(a.weekId)?.startDate??"")||(maps.area.get(a.areaCodeId)?.sortOrder??0)-(maps.area.get(b.areaCodeId)?.sortOrder??0));}
const reportSchema=z.object({weekId:z.string().uuid(),areaCodeId:z.string().uuid(),achievements:z.string().max(10000),nextPlan:z.string().max(10000),issues:z.string().max(10000),decisions:z.string().max(10000),notes:z.string().max(10000)});
export async function saveWeeklyReport(projectId:string,userId:string,input:unknown){const data=reportSchema.parse(input),records=await listDocuments<StoredReport>(projectId,"weeklyReports"),existing=records.find(row=>row.weekId===data.weekId&&row.areaCodeId===data.areaCodeId),id=existing?.id??randomUUID(),timestamp=nowIso(),stored={...data,createdBy:existing?.createdBy??userId,version:(existing?.version??0)+1,createdAt:existing?.createdAt??timestamp,updatedAt:timestamp};await projectCollection(projectId,"weeklyReports").doc(id).set(stored);await writeAuditLog(projectId,userId,`WEEKLY_REPORTS_${existing?"UPDATE":"INSERT"}`,existing??null,stored);return {id};}

export async function listWeeklyProgress(projectId:string,weekId?:string){const [records,weeks,options]=await Promise.all([listDocuments<StoredProgress>(projectId,"weeklyProgress"),listProjectWeeks(projectId),getCodeOptions(projectId)]),maps=lookupMaps(weeks,options.tracks),today=new Date().toISOString().slice(0,10);return records.filter(row=>!weekId||row.weekId===weekId).map(row=>({id:row.id,weekId:row.weekId,weekLabel:maps.week.get(row.weekId)?.label??"-",areaCodeId:row.areaCodeId,areaLabel:maps.area.get(row.areaCodeId)?.label??"-",taskName:row.taskName,planDetail:row.planDetail,planTargetDate:row.planTargetDate,actualDetail:row.actualDetail,actualDate:row.actualDate,progress:Number(row.progress),nextPlan:row.nextPlan,nextTargetDate:row.nextTargetDate,notes:row.notes,version:row.version,delayed:row.progress<100&&Boolean(row.planTargetDate&&row.planTargetDate<today)})).sort((a,b)=>(maps.week.get(b.weekId)?.startDate??"").localeCompare(maps.week.get(a.weekId)?.startDate??"")||(maps.area.get(a.areaCodeId)?.sortOrder??0)-(maps.area.get(b.areaCodeId)?.sortOrder??0));}
const progressSchema=z.object({weekId:z.string().uuid(),areaCodeId:z.string().uuid(),taskName:z.string().trim().min(1).max(200),planDetail:z.string().max(10000),planTargetDate:z.string().date().nullable(),actualDetail:z.string().max(10000),actualDate:z.string().date().nullable(),progress:z.number().min(0).max(100),nextPlan:z.string().max(10000),nextTargetDate:z.string().date().nullable(),notes:z.string().max(10000)});
export async function createProgress(projectId:string,userId:string,input:unknown){const data=progressSchema.parse(input),id=randomUUID(),timestamp=nowIso(),stored={...data,createdBy:userId,version:1,createdAt:timestamp,updatedAt:timestamp};await projectCollection(projectId,"weeklyProgress").doc(id).set(stored);await writeAuditLog(projectId,userId,"WEEKLY_PROGRESS_INSERT",null,stored);return {id};}
export async function updateProgress(projectId:string,id:string,input:unknown){const data=progressSchema.parse(input),current=await getDocument<StoredProgress>(projectId,"weeklyProgress",id);if(!current)throw new DomainError("NOT_FOUND","주간실적을 찾을 수 없습니다.");const stored={...data,createdBy:current.createdBy,version:current.version+1,createdAt:current.createdAt,updatedAt:nowIso()};await projectCollection(projectId,"weeklyProgress").doc(id).set(stored);await writeAuditLog(projectId,null,"WEEKLY_PROGRESS_UPDATE",current,stored);return {id};}

export async function listStaffChanges(projectId:string,weekId?:string){const [records,weeks,options]=await Promise.all([listDocuments<StoredStaff>(projectId,"staffChanges"),listProjectWeeks(projectId),getCodeOptions(projectId)]),maps=lookupMaps(weeks,options.tracks);return records.filter(row=>!weekId||row.weekId===weekId).map(row=>({id:row.id,weekId:row.weekId,weekLabel:maps.week.get(row.weekId)?.label??"-",areaCodeId:row.areaCodeId,areaLabel:maps.area.get(row.areaCodeId)?.label??"-",changeType:row.changeType,currentCount:row.currentCount,nextCount:row.nextCount,notes:row.notes,version:row.version})).sort((a,b)=>(maps.week.get(b.weekId)?.startDate??"").localeCompare(maps.week.get(a.weekId)?.startDate??"")||(maps.area.get(a.areaCodeId)?.sortOrder??0)-(maps.area.get(b.areaCodeId)?.sortOrder??0)||a.changeType.localeCompare(b.changeType));}
const staffSchema=z.object({weekId:z.string().uuid(),areaCodeId:z.string().uuid(),changeType:z.enum(["join","leave"]),currentCount:z.number().int().min(0),nextCount:z.number().int().min(0),notes:z.string().max(10000)});
export async function saveStaffChange(projectId:string,userId:string,input:unknown){const data=staffSchema.parse(input),records=await listDocuments<StoredStaff>(projectId,"staffChanges"),existing=records.find(row=>row.weekId===data.weekId&&row.areaCodeId===data.areaCodeId&&row.changeType===data.changeType),id=existing?.id??randomUUID(),timestamp=nowIso(),stored={...data,createdBy:existing?.createdBy??userId,version:(existing?.version??0)+1,createdAt:existing?.createdAt??timestamp,updatedAt:timestamp};await projectCollection(projectId,"staffChanges").doc(id).set(stored);await writeAuditLog(projectId,userId,`STAFF_CHANGES_${existing?"UPDATE":"INSERT"}`,existing??null,stored);return {id};}

export async function getPortfolioDashboard(projectId:string){const [weeks,reports,progress,staff,items]=await Promise.all([listProjectWeeks(projectId),listDocuments<StoredReport>(projectId,"weeklyReports"),listWeeklyProgress(projectId),listDocuments<StoredStaff>(projectId,"staffChanges"),listDocuments<{status:string;archivedAt:string|null}>(projectId,"items")]);const average=progress.length?Math.round(progress.reduce((sum,row)=>sum+row.progress,0)/progress.length*10)/10:0;return {currentWeek:weeks[0]??null,reportCount:reports.length,averageProgress:average,delayedCount:progress.filter(row=>row.delayed).length,currentStaff:staff.reduce((sum,row)=>sum+(row.changeType==="join"?row.currentCount:-row.currentCount),0),nextStaff:staff.reduce((sum,row)=>sum+(row.changeType==="join"?row.nextCount:-row.nextCount),0),openIssues:items.filter(row=>!row.archivedAt&&["registered","in_progress"].includes(row.status)).length};}
