"use client";
import { FormEvent,useState } from "react";import { useRouter } from "next/navigation";import type { CommonCode } from "@/lib/server/common-codes";import type { ProjectWeek,WeeklyReport,ProgressRow,StaffChange } from "@/lib/server/work-management";

function useSave(){const router=useRouter();const [pending,setPending]=useState(false);const [message,setMessage]=useState("");async function save(path:string,method:string,body:unknown){setPending(true);setMessage("");const r=await fetch(path,{method,headers:{"content-type":"application/json"},body:JSON.stringify(body)});const p=await r.json().catch(()=>null);setPending(false);if(!r.ok){setMessage(p?.error?.message??"저장하지 못했습니다.");return false;}router.refresh();return true;}return {pending,message,save};}
const value=(d:FormData,n:string)=>String(d.get(n)??"");const nullable=(d:FormData,n:string)=>value(d,n)||null;

export function WeekCreateForm(){const x=useSave();async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget,d=new FormData(f);if(await x.save("/api/v1/weeks","POST",{weekKey:value(d,"weekKey"),label:value(d,"label"),startDate:value(d,"startDate"),endDate:value(d,"endDate")}))f.reset();}return <form className="inline-create" onSubmit={submit}><label>주차 코드<input name="weekKey" placeholder="2026-W33" required/></label><label>주차명<input name="label" placeholder="2026년 33주차" required/></label><label>시작일<input name="startDate" type="date" required/></label><label>종료일<input name="endDate" type="date" required/></label><button className="button secondary" disabled={x.pending}>주차 추가</button>{x.message&&<span className="form-error">{x.message}</span>}</form>}

export function ReportForm({weeks,areas,report}:{weeks:ProjectWeek[];areas:CommonCode[];report?:WeeklyReport}){const x=useSave();async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await x.save("/api/v1/weekly-reports","POST",{weekId:value(d,"weekId"),areaCodeId:value(d,"areaCodeId"),achievements:value(d,"achievements"),nextPlan:value(d,"nextPlan"),issues:value(d,"issues"),decisions:value(d,"decisions"),notes:value(d,"notes")});}return <form className="work-form" onSubmit={submit}><div className="form-grid"><label>주차<select name="weekId" defaultValue={report?.weekId??weeks[0]?.id}>{weeks.map(w=><option value={w.id} key={w.id}>{w.label}</option>)}</select></label><label>영역<select name="areaCodeId" defaultValue={report?.areaCodeId}>{areas.map(a=><option value={a.id} key={a.id}>{a.label}</option>)}</select></label></div><div className="form-grid"><label>금주 실적<textarea name="achievements" rows={4} defaultValue={report?.achievements}/></label><label>차주 계획<textarea name="nextPlan" rows={4} defaultValue={report?.nextPlan}/></label><label>이슈사항<textarea name="issues" rows={3} defaultValue={report?.issues}/></label><label>의사결정 필요사항<textarea name="decisions" rows={3} defaultValue={report?.decisions}/></label></div><label>비고<textarea name="notes" rows={2} defaultValue={report?.notes}/></label>{x.message&&<p className="form-error">{x.message}</p>}<button className="button primary" disabled={x.pending}>{x.pending?"저장 중…":"주간보고 저장"}</button></form>}

export function ProgressForm({weeks,areas,row}:{weeks:ProjectWeek[];areas:CommonCode[];row?:ProgressRow}){const x=useSave();async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await x.save(row?`/api/v1/weekly-progress/${row.id}`:"/api/v1/weekly-progress",row?"PATCH":"POST",{weekId:value(d,"weekId"),areaCodeId:value(d,"areaCodeId"),taskName:value(d,"taskName"),planDetail:value(d,"planDetail"),planTargetDate:nullable(d,"planTargetDate"),actualDetail:value(d,"actualDetail"),actualDate:nullable(d,"actualDate"),progress:Number(d.get("progress")),nextPlan:value(d,"nextPlan"),nextTargetDate:nullable(d,"nextTargetDate"),notes:value(d,"notes")});}return <form className="work-form" onSubmit={submit}><div className="form-grid triple"><label>주차<select name="weekId" defaultValue={row?.weekId??weeks[0]?.id}>{weeks.map(w=><option value={w.id} key={w.id}>{w.label}</option>)}</select></label><label>영역<select name="areaCodeId" defaultValue={row?.areaCodeId}>{areas.map(a=><option value={a.id} key={a.id}>{a.label}</option>)}</select></label><label>공정률(%)<input name="progress" type="number" min="0" max="100" step="1" defaultValue={row?.progress??0}/></label></div><label>업무명<input name="taskName" defaultValue={row?.taskName} required maxLength={200}/></label><div className="form-grid triple"><label>금주 계획<textarea name="planDetail" rows={3} defaultValue={row?.planDetail}/></label><label>계획 목표일<input name="planTargetDate" type="date" defaultValue={row?.planTargetDate??""}/></label><label>실제 완료일<input name="actualDate" type="date" defaultValue={row?.actualDate??""}/></label><label>금주 실적<textarea name="actualDetail" rows={3} defaultValue={row?.actualDetail}/></label><label>차주 계획<textarea name="nextPlan" rows={3} defaultValue={row?.nextPlan}/></label><label>차주 목표일<input name="nextTargetDate" type="date" defaultValue={row?.nextTargetDate??""}/></label></div><label>비고<input name="notes" defaultValue={row?.notes}/></label>{x.message&&<p className="form-error">{x.message}</p>}<button className="button primary" disabled={x.pending}>{x.pending?"저장 중…":row?"실적 수정":"실적 추가"}</button></form>}

export function StaffForm({weeks,areas,row}:{weeks:ProjectWeek[];areas:CommonCode[];row?:StaffChange}){const x=useSave();async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await x.save("/api/v1/staff-changes","POST",{weekId:value(d,"weekId"),areaCodeId:value(d,"areaCodeId"),changeType:value(d,"changeType"),currentCount:Number(d.get("currentCount")),nextCount:Number(d.get("nextCount")),notes:value(d,"notes")});}return <form className="work-form" onSubmit={submit}><div className="form-grid triple"><label>주차<select name="weekId" defaultValue={row?.weekId??weeks[0]?.id}>{weeks.map(w=><option value={w.id} key={w.id}>{w.label}</option>)}</select></label><label>영역<select name="areaCodeId" defaultValue={row?.areaCodeId}>{areas.map(a=><option value={a.id} key={a.id}>{a.label}</option>)}</select></label><label>구분<select name="changeType" defaultValue={row?.changeType??"join"}><option value="join">투입</option><option value="leave">철수</option></select></label><label>금주 인원<input name="currentCount" type="number" min="0" defaultValue={row?.currentCount??0}/></label><label>차주 인원<input name="nextCount" type="number" min="0" defaultValue={row?.nextCount??0}/></label><label>비고<input name="notes" defaultValue={row?.notes}/></label></div>{x.message&&<p className="form-error">{x.message}</p>}<button className="button primary" disabled={x.pending}>{x.pending?"저장 중…":"인력변동 저장"}</button></form>}
