import Link from "next/link";
import { ClickableTableRow } from "@/components/ClickableTableRow";
import { WORK_LOG_STATUSES, workLogStatusLabel } from "@/lib/domain/work-logs";
import type { getWorkLogIdentity, WorkLogListResult } from "@/lib/server/work-logs";

type Filters = { q: string; dateFrom: string; dateTo: string; groupId: string; assigneeId: string; status: string; page: number; pageSize: number | "all" };
function queryString(filters: Filters, overrides: Record<string, string | number | undefined> = {}) { const p = new URLSearchParams(); Object.entries({ ...filters, ...overrides }).forEach(([key, value]) => { if (value !== "" && value != null && !(key === "page" && value === 1) && !(key === "pageSize" && value === 20)) p.set(key, String(value)); }); return p.toString(); }

type Identity = Awaited<ReturnType<typeof getWorkLogIdentity>>;

export function WorkLogListScreen({ result, filters, identity }: { result: WorkLogListResult; filters: Filters; identity: Identity }) {
  const pageLinkCount = Math.min(10, result.totalPages);
  const firstPage = Math.max(1, Math.min(result.page - 4, result.totalPages - pageLinkCount + 1));
  const pageNumbers = Array.from({ length: pageLinkCount }, (_, index) => firstPage + index);
  return <><header className="topbar"><div><h1>업무일지</h1><p>총 {result.total}건 · 작업자별 일일 업무내용</p></div></header><div className="content">
    <div className="work-log-fixed-identity panel compact"><div><span>담당자</span><strong>{identity.name} ({identity.loginId})</strong></div><div><span>업무그룹</span><strong>{identity.group?.label ?? "미지정"}</strong></div></div>
    <form className="filters inline-filter work-log-filters" method="get">{filters.pageSize !== 20 && <input type="hidden" name="pageSize" value={String(filters.pageSize)} />}<input name="q" defaultValue={filters.q} placeholder="번호·WBS·업무내용 검색" aria-label="검색어" /><label>시작일<input type="date" name="dateFrom" defaultValue={filters.dateFrom} /></label><label>종료일<input type="date" name="dateTo" defaultValue={filters.dateTo} /></label><select name="status" defaultValue={filters.status} aria-label="진행상태"><option value="">전체 진행상태</option>{WORK_LOG_STATUSES.map((s) => <option value={s.value} key={s.value}>{s.label}</option>)}</select><button className="button secondary">조회</button><Link className="button ghost" href="/work-logs">초기화</Link><Link className="button primary filter-primary-action" href="/work-logs/new">+ 업무일지 작성</Link></form>
    <section className="panel compact">{result.rows.length ? <div className="table-wrap"><table className="work-log-list-table"><thead><tr><th>번호</th><th>업무일자</th><th>업무그룹</th><th>담당자</th><th>WBS번호</th><th>진행상태</th><th>업무내용</th><th>최종수정</th></tr></thead><tbody>{result.rows.map((row) => <ClickableTableRow href={`/work-logs/${row.id}`} ariaLabel={`${row.displayId} 업무일지 상세보기`} key={row.id}><td className="mono"><Link className="table-link" href={`/work-logs/${row.id}`}>{row.displayId}</Link></td><td>{row.workDate}</td><td>{row.groupLabel}</td><td>{row.assigneeName}</td><td className="mono">{row.wbsNumber || "-"}</td><td><span className={`badge ${row.status === "COMPLETED" ? "band-green" : "band-yellow"}`}>{workLogStatusLabel(row.status)}</span></td><td className="title-cell work-log-content-cell">{row.workContent}</td><td>{new Intl.DateTimeFormat("ko-KR", { dateStyle: "short", timeStyle: "short", timeZone: "Asia/Seoul" }).format(new Date(row.updatedAt))}</td></ClickableTableRow>)}</tbody></table></div> : <div className="empty">조건에 맞는 업무일지가 없습니다.</div>}</section>
    {result.total > 0 && <nav className="pagination requirement-pagination" aria-label="페이지 이동"><form className="page-size-form" method="get">{filters.q && <input type="hidden" name="q" value={filters.q} />}{filters.dateFrom && <input type="hidden" name="dateFrom" value={filters.dateFrom} />}{filters.dateTo && <input type="hidden" name="dateTo" value={filters.dateTo} />}{filters.status && <input type="hidden" name="status" value={filters.status} />}<label>표시 개수<select name="pageSize" defaultValue={String(filters.pageSize)}><option value="20">20개</option><option value="40">40개</option><option value="60">60개</option><option value="80">80개</option><option value="100">100개</option><option value="all">전체</option></select></label><button className="button secondary" type="submit">적용</button></form><div className="page-links">{result.page > 1 && <Link href={`/work-logs?${queryString(filters, { page: result.page - 1 })}`} aria-label="이전 페이지">이전</Link>}{pageNumbers.map((page) => page === result.page ? <strong className="current" aria-current="page" key={page}>{page}</strong> : <Link href={`/work-logs?${queryString(filters, { page })}`} key={page}>{page}</Link>)}{result.page < result.totalPages && <Link href={`/work-logs?${queryString(filters, { page: result.page + 1 })}`} aria-label="다음 페이지">다음</Link>}</div><span className="page-summary">총 {result.total}건 · {result.page} / {result.totalPages} 페이지</span></nav>}
  </div></>;
}
