"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { PersonPicker } from "@/components/PersonPicker";

type Room = { id:string; name:string; roomType:"LARGE"|"SMALL"; capacity:number; floor:string|null; equipment:string[]; isActive:boolean; deletedAt:string|null };
type Member = { id:string; userId:string; name:string };
type Attendee = { id:string; name:string; department:string|null };
type Reservation = { id:string; roomId:string; roomName:string; userId:string; userName:string; department:string|null; startAt:string; endAt:string; purpose:string; recurring:boolean; attendees:Attendee[] };
type Recurring = { id:string; applicantId:string; patternType:string; startMinutes:number; endMinutes:number; periodStart:string; periodEnd:string; purpose:string; status:string; rejectReason:string|null; room:{name:string}; applicant:{name:string;department:string|null} };
type Tab="board"|"mine"|"recurring"; type View="day"|"week"|"month";
const START=540,END=1140,SLOT=30,SLOTS=Array.from({length:(END-START)/SLOT},(_,i)=>START+i*SLOT);
const hhmm=(m:number)=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
const toMinutes=(value:string)=>{const[h,m]=value.split(":").map(Number);return h*60+m};
const slotOf=(value:string)=>{const total=Math.min(Math.max(toMinutes(value),START),END-SLOT);return total-(total%SLOT)};
const time=(iso:string)=>new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Seoul",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(iso));
const dayKey=(iso:string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul"}).format(new Date(iso));
const dateLabel=(date:string)=>new Intl.DateTimeFormat("ko-KR",{timeZone:"UTC",month:"long",day:"numeric",weekday:"long"}).format(new Date(`${date}T00:00:00Z`));
const dateTime=(date:string,value:string)=>`${date}T${value}:00+09:00`;
const api=async(url:string,init?:RequestInit)=>{const response=await fetch(url,init),body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message??"요청을 처리하지 못했습니다.");return body.data};
function range(date:string,view:View){const selected=new Date(`${date}T00:00:00Z`);let from=selected,to:Date;if(view==="day")to=new Date(selected.getTime()+86400000);else if(view==="week"){from=new Date(selected);from.setUTCDate(from.getUTCDate()-((from.getUTCDay()+6)%7));to=new Date(from.getTime()+7*86400000)}else{from=new Date(Date.UTC(selected.getUTCFullYear(),selected.getUTCMonth(),1));to=new Date(Date.UTC(selected.getUTCFullYear(),selected.getUTCMonth()+1,1))}return{from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10)}}
function daysBetween(from:string,to:string){const result:string[]=[];for(let d=new Date(`${from}T00:00:00Z`),e=new Date(`${to}T00:00:00Z`);d<e;d=new Date(d.getTime()+86400000))result.push(d.toISOString().slice(0,10));return result}

export function MeetingRoomScreen({initialDate,initialRooms,initialReservations,initialRecurring,members,currentUserId,isAdmin,readOnly=false,embedded=false}:{initialDate:string;initialRooms:Room[];initialReservations:Reservation[];initialRecurring:Recurring[];members:Member[];currentUserId:string|null;isAdmin:boolean;readOnly?:boolean;embedded?:boolean}){
  const router=useRouter();const[tab,setTab]=useState<Tab>("board"),[view,setView]=useState<View>("day"),[date,setDate]=useState(initialDate),rooms=initialRooms,[reservations,setReservations]=useState(initialReservations),[recurring,setRecurring]=useState(initialRecurring),[message,setMessage]=useState(""),[detail,setDetail]=useState<Reservation|null>(null);
  const[booking,setBooking]=useState<{roomId:string;date:string;start:string;end:string;purpose:string;attendeeIds:string[];attendeeNames:string[]}|null>(null);const activeRooms=rooms.filter(r=>!r.deletedAt&&r.isActive);const currentRange=range(date,view);
  async function reload(targetDate=date,targetView=view){const r=range(targetDate,targetView);setReservations(await api(`/api/v1/meeting-reservations?from=${encodeURIComponent(`${r.from}T00:00:00+09:00`)}&to=${encodeURIComponent(`${r.to}T00:00:00+09:00`)}`))}
  async function changeView(next:View){setView(next);await reload(date,next)}
  async function move(step:number){const d=new Date(`${date}T00:00:00Z`);if(view==="month")d.setUTCMonth(d.getUTCMonth()+step);else d.setUTCDate(d.getUTCDate()+step*(view==="week"?7:1));const next=d.toISOString().slice(0,10);setDate(next);await reload(next,view)}
  async function submitBooking(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!booking)return;try{await api("/api/v1/meeting-reservations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({roomId:booking.roomId,startAt:dateTime(booking.date,booking.start),endAt:dateTime(booking.date,booking.end),purpose:booking.purpose,attendeeIds:booking.attendeeIds,attendeeNames:booking.attendeeNames})});setBooking(null);await reload();setMessage("")}catch(err){setMessage((err as Error).message)}}
  async function cancel(id:string){if(!confirm("예약을 취소하시겠습니까?"))return;try{await api(`/api/v1/meeting-reservations/${id}/cancel`,{method:"PATCH"});setDetail(null);await reload();setMessage("예약이 취소되었습니다.")}catch(err){setMessage((err as Error).message)}}
  async function saveReservation(id:string,body:unknown):Promise<string|null>{try{await api(`/api/v1/meeting-reservations/${id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(body)});setDetail(null);await reload();setMessage("예약 정보를 저장했습니다.");return null}catch(err){return (err as Error).message}}
  const mine=currentUserId?reservations.filter(r=>r.userId===currentUserId):[];
  return <><header className="topbar"><div><h1>{readOnly?"회의실 예약현황":"회의실 예약"}</h1>{!readOnly&&<p>일간·주간·월간 사용현황과 참석자를 관리합니다.</p>}</div>{readOnly&&!embedded&&<Link className="button primary" href="/login?callbackUrl=%2Fmeetrooms">로그인</Link>}</header><div className="content meeting-content">
    {!readOnly&&<nav className="meeting-tabs">{([["board","사용현황"],["mine","내 예약"],["recurring","정기예약 신청"]] as [Tab,string][]).map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>}{message&&<p className="action-message" role="status">{message}</p>}
    {tab==="board"&&<section className="panel meeting-board"><div className="meeting-toolbar"><div className="meeting-date-nav"><button className="button secondary" onClick={()=>move(-1)} aria-label="이전 기간">‹</button><input type="date" aria-label="조회 날짜" value={date} onChange={async e=>{setDate(e.target.value);await reload(e.target.value,view)}}/><button className="button secondary" onClick={()=>move(1)} aria-label="다음 기간">›</button></div>{view==="day"&&<strong className="meeting-date-label">{dateLabel(date)}</strong>}<div className="view-switch">{(["day","week","month"] as View[]).map(v=><button className={`button ${view===v?"primary":"secondary"}`} onClick={()=>changeView(v)} key={v}>{v==="day"?"일간":v==="week"?"주간":"월간"}</button>)}</div></div>{view==="day"?<DayBoard rooms={activeRooms} reservations={reservations} onCreate={readOnly?undefined:setBooking} onDetail={setDetail} date={date}/>:<PeriodBoard view={view} range={currentRange} reservations={reservations} onDetail={setDetail}/>}</section>}
    {tab==="mine"&&<ReservationList title="내 예약" reservations={mine} onDetail={setDetail}/>} {tab==="recurring"&&<RecurringPanel rooms={activeRooms} recurring={recurring} setMessage={setMessage} onChanged={async()=>{setRecurring(await api("/api/v1/recurring-meetings"));await reload()}}/>}
  </div>{booking&&<BookingModal booking={booking} roomName={rooms.find(r=>r.id===booking.roomId)?.name??""} members={members.filter(m=>m.id!==currentUserId)} setBooking={setBooking} onSubmit={submitBooking}/>} {detail&&<DetailModal reservation={detail} members={members} canEdit={isAdmin||detail.userId===currentUserId} onClose={()=>setDetail(null)} onCancel={()=>cancel(detail.id)} onSave={saveReservation}/>}</>;
}

function DayBoard({rooms,reservations,onCreate,onDetail,date}:{rooms:Room[];reservations:Reservation[];onCreate?:((value:{roomId:string;date:string;start:string;end:string;purpose:string;attendeeIds:string[];attendeeNames:string[]})=>void);onDetail:(r:Reservation)=>void;date:string}){return <><div className="day-overview"><div><span className="day-overview-label">일일 예약현황</span><h2>{dateLabel(date)}</h2><p>{onCreate?"빈 시간대를 선택하면 바로 예약할 수 있습니다.":"예약된 시간과 이용 가능한 시간대를 확인할 수 있습니다."}</p></div><dl><div><dt>운영 회의실</dt><dd>{rooms.length}</dd></div><div><dt>오늘 예약</dt><dd>{reservations.length}</dd></div></dl></div>{rooms.length?<div className="meeting-grid" style={{gridTemplateColumns:`76px repeat(${rooms.length},minmax(170px,1fr))`}}><div className="meeting-time-head"><span>시간</span></div>{rooms.map(r=><div className="meeting-room-head" key={r.id}><span className={`room-type ${r.roomType.toLowerCase()}`}>{r.roomType==="LARGE"?"대회의실":"소회의실"}</span><strong>{r.name}</strong><small>{r.floor??"위치 미정"} · 최대 {r.capacity}명</small></div>)}{SLOTS.map(slot=><div style={{display:"contents"}} key={slot}><time className={slot%60===0?"hour":""}>{slot%60===0?hhmm(slot):""}</time>{rooms.map(room=>{const found=reservations.find(r=>r.roomId===room.id&&time(r.startAt)===hhmm(slot)),occupied=reservations.some(r=>r.roomId===room.id&&time(r.startAt)<hhmm(slot)&&time(r.endAt)>hhmm(slot));return found?<button className={`meeting-event ${found.recurring?"recurring":""} ${slot%60===0?"hour":""}`} style={{gridRow:`span ${Math.max(1,(new Date(found.endAt).getTime()-new Date(found.startAt).getTime())/1800000)}`}} onClick={()=>onDetail(found)} key={room.id}><strong>{found.purpose}</strong><small>{time(found.startAt)}–{time(found.endAt)}</small><span>{found.userName} · {found.attendees.length}명</span></button>:occupied?null:onCreate?<button className={`meeting-slot ${slot%60===0?"hour":""}`} aria-label={`${room.name} ${hhmm(slot)} 예약`} title={`${hhmm(slot)} 예약하기`} onClick={()=>onCreate({roomId:room.id,date,start:hhmm(slot),end:hhmm(Math.min(slot+60,END)),purpose:"",attendeeIds:[],attendeeNames:[]})} key={room.id}><span>+</span></button>:<div className={`meeting-slot readonly ${slot%60===0?"hour":""}`} aria-label={`${room.name} ${hhmm(slot)} 이용 가능`} key={room.id}/>})}</div>)}</div>:<p className="empty meeting-empty">운영 중인 회의실이 없습니다.</p>}</>}
function PeriodBoard({view,range:period,reservations,onDetail}:{view:View;range:{from:string;to:string};reservations:Reservation[];onDetail:(r:Reservation)=>void}){
  const days=daysBetween(period.from,period.to);const today=dayKey(new Date().toISOString());
  if(view==="week")return <div className="calendar-time-grid week" style={{gridTemplateColumns:`60px repeat(${days.length},minmax(120px,1fr))`}}>
    <div className="calendar-time-corner" />
    {days.map(day=><div className={`calendar-time-daycol ${day===today?"today":""}`} key={day}><strong>{new Intl.DateTimeFormat("ko-KR",{weekday:"short",timeZone:"UTC"}).format(new Date(`${day}T00:00:00Z`))}</strong><span>{Number(day.slice(8))}</span></div>)}
    {SLOTS.map(slot=><div style={{display:"contents"}} key={slot}>
      <time className={slot%60===0?"hour":""}>{slot%60===0?hhmm(slot):""}</time>
      {days.map(day=>{const items=reservations.filter(r=>dayKey(r.startAt)===day&&slotOf(time(r.startAt))===slot);return <div className={`calendar-time-cell ${slot%60===0?"hour":""}`} key={day}>{items.map(r=><button className="calendar-event" onClick={()=>onDetail(r)} key={r.id}><span>{time(r.startAt)}</span><strong>{r.roomName}</strong><small>{r.purpose}</small></button>)}</div>})}
    </div>)}
  </div>;
  return <div className="meeting-month">{days.map(day=>{const items=reservations.filter(r=>dayKey(r.startAt)===day);return <section className={`period-day ${day===today?"today":""}`} key={day}><header><strong>{Number(day.slice(8))}</strong><span>{items.length}건</span></header><div>{items.map(r=><button className="period-event" onClick={()=>onDetail(r)} key={r.id}><time>{time(r.startAt)}</time><strong>{r.roomName}</strong><span>{r.purpose}</span></button>)}</div></section>})}</div>;
}
function ReservationList({title,reservations,onDetail}:{title:string;reservations:Reservation[];onDetail:(r:Reservation)=>void}){return <section className="panel"><div className="panel-head"><h2>{title}</h2><span>{reservations.length}건</span></div><div className="meeting-list">{reservations.map(r=><button className="reservation-row" onClick={()=>onDetail(r)} key={r.id}><strong>{r.roomName}</strong><span>{dayKey(r.startAt)} {time(r.startAt)}–{time(r.endAt)}</span><span>{r.purpose}</span><small>참석자 {r.attendees.length}명</small></button>)}{!reservations.length&&<p className="empty">예약이 없습니다.</p>}</div></section>}
function BookingModal({booking,roomName,members,setBooking,onSubmit}:{booking:any;roomName:string;members:Member[];setBooking:(v:any)=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal-card" onSubmit={onSubmit}><h2>회의실 예약</h2><label>회의실<input value={roomName} disabled/></label><label>예약일<input type="date" value={booking.date} onChange={e=>setBooking({...booking,date:e.target.value})}/></label><div className="form-grid two"><label>시작<input type="time" min="09:00" max="19:00" step="1800" value={booking.start} onChange={e=>setBooking({...booking,start:e.target.value})}/></label><label>종료<input type="time" min="09:00" max="19:00" step="1800" value={booking.end} onChange={e=>setBooking({...booking,end:e.target.value})}/></label></div><label>사용 목적<input required maxLength={500} value={booking.purpose} onChange={e=>setBooking({...booking,purpose:e.target.value})}/></label><fieldset className="attendee-picker"><legend>참석자 선택 ({booking.attendeeIds.length+booking.attendeeNames.length}명)</legend><PersonPicker people={members} selectedIds={booking.attendeeIds} selectedNames={booking.attendeeNames} onChange={(attendeeIds,attendeeNames)=>setBooking({...booking,attendeeIds,attendeeNames})}/></fieldset><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setBooking(null)}>닫기</button><button className="button primary">예약</button></div></form></div>}
function DetailModal({reservation,members,canEdit,onClose,onCancel,onSave}:{reservation:Reservation;members:Member[];canEdit:boolean;onClose:()=>void;onCancel:()=>void;onSave:(id:string,body:unknown)=>Promise<string|null>}){
  const[editing,setEditing]=useState(false),[pending,setPending]=useState(false),[message,setMessage]=useState("");
  const memberIds=useMemo(()=>new Set(members.map(m=>m.id)),[members]);
  const initialAttendeeIds=reservation.attendees.filter(a=>memberIds.has(a.id)).map(a=>a.id);
  const initialAttendeeNames=reservation.attendees.filter(a=>!memberIds.has(a.id)).map(a=>a.name);
  const[form,setForm]=useState(()=>({date:dayKey(reservation.startAt),start:time(reservation.startAt),end:time(reservation.endAt),purpose:reservation.purpose,attendeeIds:initialAttendeeIds,attendeeNames:initialAttendeeNames}));
  function startEdit(){setForm({date:dayKey(reservation.startAt),start:time(reservation.startAt),end:time(reservation.endAt),purpose:reservation.purpose,attendeeIds:initialAttendeeIds,attendeeNames:initialAttendeeNames});setMessage("");setEditing(true)}
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();setPending(true);setMessage("");const err=await onSave(reservation.id,{startAt:dateTime(form.date,form.start),endAt:dateTime(form.date,form.end),purpose:form.purpose,attendeeIds:form.attendeeIds,attendeeNames:form.attendeeNames});setPending(false);if(err)setMessage(err);else setEditing(false)}
  if(editing)return <div className="modal-backdrop"><form className="modal-card" onSubmit={save}><h2>예약 정보 수정</h2>
    <label>회의실<input value={reservation.roomName} disabled/></label>
    <label>예약자<input value={`${reservation.userName}${reservation.department?` · ${reservation.department}`:""}`} disabled/></label>
    <label>예약일<input type="date" value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/></label>
    <div className="form-grid two"><label>시작<input type="time" min="09:00" max="19:00" step="1800" value={form.start} onChange={e=>setForm({...form,start:e.target.value})}/></label><label>종료<input type="time" min="09:00" max="19:00" step="1800" value={form.end} onChange={e=>setForm({...form,end:e.target.value})}/></label></div>
    <label>사용 목적<input required maxLength={500} value={form.purpose} onChange={e=>setForm({...form,purpose:e.target.value})}/></label>
    <fieldset className="attendee-picker"><legend>참석자 선택 ({form.attendeeIds.length+form.attendeeNames.length}명)</legend><PersonPicker people={members.filter(m=>m.id!==reservation.userId)} selectedIds={form.attendeeIds} selectedNames={form.attendeeNames} onChange={(attendeeIds,attendeeNames)=>setForm({...form,attendeeIds,attendeeNames})}/></fieldset>
    {message&&<p className="form-error">{message}</p>}
    <div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setEditing(false)} disabled={pending}>취소</button><button className="button primary" disabled={pending}>{pending?"저장 중…":"저장"}</button></div>
  </form></div>;
  return <div className="modal-backdrop"><section className="modal-card reservation-detail"><h2>예약 상세</h2><dl><dt>회의실</dt><dd>{reservation.roomName}</dd><dt>일시</dt><dd>{dayKey(reservation.startAt)} {time(reservation.startAt)}–{time(reservation.endAt)}</dd><dt>예약자</dt><dd>{reservation.userName}{reservation.department?` · ${reservation.department}`:""}</dd><dt>사용 목적</dt><dd>{reservation.purpose}</dd><dt>예약 유형</dt><dd>{reservation.recurring?"정기예약":"일반예약"}</dd><dt>참석자</dt><dd>{reservation.attendees.length?reservation.attendees.map(a=>`${a.name}${a.department?`(${a.department})`:""}`).join(", "):"등록된 참석자 없음"}</dd></dl><div className="modal-actions">{canEdit&&<><button className="button secondary" onClick={startEdit}>예약 정보 수정</button><button className="button danger" onClick={onCancel}>예약 취소</button></>}<button className="button primary" onClick={onClose}>닫기</button></div></section></div>;
}

function RecurringPanel({rooms,recurring,setMessage,onChanged}:{rooms:Room[];recurring:Recurring[];setMessage:(s:string)=>void;onChanged:()=>Promise<void>}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/v1/recurring-meetings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({roomId:f.get("roomId"),patternType:f.get("patternType"),daysOfWeek:f.getAll("days").map(Number),dayOfMonth:Number(f.get("dayOfMonth"))||undefined,startMinutes:toMinutes(String(f.get("start"))),endMinutes:toMinutes(String(f.get("end"))),periodStart:f.get("periodStart"),periodEnd:f.get("periodEnd"),purpose:f.get("purpose")})});e.currentTarget.reset();await onChanged();setMessage("정기예약 신청이 접수되었습니다.")}catch(err){setMessage((err as Error).message)}}return <div className="meeting-split"><form className="panel meeting-form" onSubmit={submit}><h2>정기예약 신청</h2><label>회의실<select name="roomId">{rooms.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><label>반복<select name="patternType"><option value="WEEKLY">매주</option><option value="DAILY">매일</option><option value="MONTHLY">매월</option></select></label><fieldset><legend>요일</legend>{[1,2,3,4,5,6,7].map((d,i)=><label className="check" key={d}><input type="checkbox" name="days" value={d}/>{"월화수목금토일"[i]}</label>)}</fieldset><label>매월 일자<input name="dayOfMonth" type="number" min="1" max="31"/></label><div className="form-grid two"><label>시작<input name="start" type="time" defaultValue="10:00" required/></label><label>종료<input name="end" type="time" defaultValue="11:00" required/></label><label>기간 시작<input name="periodStart" type="date" required/></label><label>기간 종료<input name="periodEnd" type="date" required/></label></div><label>목적<input name="purpose" required/></label><button className="button primary">신청</button></form><section className="panel"><div className="panel-head"><h2>신청 내역</h2><span>{recurring.length}건</span></div><div className="meeting-list">{recurring.map(r=><article key={r.id}><div><strong>{r.room.name} · {r.applicant.name}</strong><p>{r.patternType} · {hhmm(r.startMinutes)}–{hhmm(r.endMinutes)} · {r.purpose} · {r.status}</p></div></article>)}</div></section></div>}
