"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type Room = { id:string; name:string; roomType:"LARGE"|"SMALL"; capacity:number; floor:string|null; equipment:string[]; isActive:boolean; deletedAt:string|null };
type Member = { id:string; userId:string; name:string };
type Attendee = { id:string; name:string; department:string|null };
type Reservation = { id:string; roomId:string; roomName:string; userId:string; userName:string; department:string|null; startAt:string; endAt:string; purpose:string; recurring:boolean; attendees:Attendee[] };
type Recurring = { id:string; applicantId:string; patternType:string; startMinutes:number; endMinutes:number; periodStart:string; periodEnd:string; purpose:string; status:string; rejectReason:string|null; room:{name:string}; applicant:{name:string;department:string|null} };
type Tab="board"|"mine"|"recurring"|"rooms"; type View="day"|"week"|"month";
const START=540,END=1140,SLOT=30,SLOTS=Array.from({length:(END-START)/SLOT},(_,i)=>START+i*SLOT);
const hhmm=(m:number)=>`${String(Math.floor(m/60)).padStart(2,"0")}:${String(m%60).padStart(2,"0")}`;
const time=(iso:string)=>new Intl.DateTimeFormat("en-GB",{timeZone:"Asia/Seoul",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).format(new Date(iso));
const dayKey=(iso:string)=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Seoul"}).format(new Date(iso));
const dateLabel=(date:string)=>new Intl.DateTimeFormat("ko-KR",{timeZone:"UTC",month:"long",day:"numeric",weekday:"long"}).format(new Date(`${date}T00:00:00Z`));
const dateTime=(date:string,value:string)=>`${date}T${value}:00+09:00`;
const api=async(url:string,init?:RequestInit)=>{const response=await fetch(url,init),body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.error?.message??"요청을 처리하지 못했습니다.");return body.data};
function range(date:string,view:View){const selected=new Date(`${date}T00:00:00Z`);let from=selected,to:Date;if(view==="day")to=new Date(selected.getTime()+86400000);else if(view==="week"){from=new Date(selected);from.setUTCDate(from.getUTCDate()-((from.getUTCDay()+6)%7));to=new Date(from.getTime()+7*86400000)}else{from=new Date(Date.UTC(selected.getUTCFullYear(),selected.getUTCMonth(),1));to=new Date(Date.UTC(selected.getUTCFullYear(),selected.getUTCMonth()+1,1))}return{from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10)}}
function daysBetween(from:string,to:string){const result:string[]=[];for(let d=new Date(`${from}T00:00:00Z`),e=new Date(`${to}T00:00:00Z`);d<e;d=new Date(d.getTime()+86400000))result.push(d.toISOString().slice(0,10));return result}

export function MeetingRoomScreen({initialDate,initialRooms,initialReservations,initialRecurring,members,currentUserId,isAdmin}:{initialDate:string;initialRooms:Room[];initialReservations:Reservation[];initialRecurring:Recurring[];members:Member[];currentUserId:string;isAdmin:boolean}){
  const router=useRouter();const[tab,setTab]=useState<Tab>("board"),[view,setView]=useState<View>("day"),[date,setDate]=useState(initialDate),[rooms,setRooms]=useState(initialRooms),[reservations,setReservations]=useState(initialReservations),[recurring,setRecurring]=useState(initialRecurring),[message,setMessage]=useState(""),[detail,setDetail]=useState<Reservation|null>(null);
  const[booking,setBooking]=useState<{roomId:string;date:string;start:string;end:string;purpose:string;attendeeIds:string[]}|null>(null);const activeRooms=rooms.filter(r=>!r.deletedAt&&r.isActive);const currentRange=range(date,view);
  async function reload(targetDate=date,targetView=view){const r=range(targetDate,targetView);setReservations(await api(`/api/v1/meeting-reservations?from=${encodeURIComponent(`${r.from}T00:00:00+09:00`)}&to=${encodeURIComponent(`${r.to}T00:00:00+09:00`)}`))}
  async function changeView(next:View){setView(next);await reload(date,next)}
  async function move(step:number){const d=new Date(`${date}T00:00:00Z`);if(view==="month")d.setUTCMonth(d.getUTCMonth()+step);else d.setUTCDate(d.getUTCDate()+step*(view==="week"?7:1));const next=d.toISOString().slice(0,10);setDate(next);await reload(next,view)}
  async function submitBooking(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!booking)return;try{await api("/api/v1/meeting-reservations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({roomId:booking.roomId,startAt:dateTime(booking.date,booking.start),endAt:dateTime(booking.date,booking.end),purpose:booking.purpose,attendeeIds:booking.attendeeIds})});setBooking(null);await reload();setMessage("")}catch(err){setMessage((err as Error).message)}}
  async function cancel(id:string){if(!confirm("예약을 취소하시겠습니까?"))return;try{await api(`/api/v1/meeting-reservations/${id}/cancel`,{method:"PATCH"});setDetail(null);await reload();setMessage("예약이 취소되었습니다.")}catch(err){setMessage((err as Error).message)}}
  async function changeTime(r:Reservation){const s=prompt("변경할 시작 시간(HH:MM)",time(r.startAt)),e=s&&prompt("변경할 종료 시간(HH:MM)",time(r.endAt));if(!s||!e)return;try{await api(`/api/v1/meeting-reservations/${r.id}/time`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({startAt:dateTime(dayKey(r.startAt),s),endAt:dateTime(dayKey(r.endAt),e)})});setDetail(null);await reload();setMessage("예약 시간을 변경했습니다.")}catch(err){setMessage((err as Error).message)}}
  const mine=reservations.filter(r=>r.userId===currentUserId);
  return <><header className="topbar"><div><h1>회의실 예약</h1><p>일간·주간·월간 사용현황과 참석자를 관리합니다.</p></div></header><div className="content meeting-content">
    <nav className="meeting-tabs">{([["board","사용현황"],["mine","내 예약"],["recurring",isAdmin?"정기예약 승인":"정기예약 신청"],...(isAdmin?[["rooms","회의실 관리"]]:[])] as [Tab,string][]).map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>{message&&<p className="action-message" role="status">{message}</p>}
    {tab==="board"&&<section className="panel meeting-board"><div className="meeting-toolbar"><div className="meeting-date-nav"><button className="button secondary" onClick={()=>move(-1)} aria-label="이전 기간">‹</button><input type="date" aria-label="조회 날짜" value={date} onChange={async e=>{setDate(e.target.value);await reload(e.target.value,view)}}/><button className="button secondary" onClick={()=>move(1)} aria-label="다음 기간">›</button></div>{view==="day"&&<strong className="meeting-date-label">{dateLabel(date)}</strong>}<div className="view-switch">{(["day","week","month"] as View[]).map(v=><button className={`button ${view===v?"primary":"secondary"}`} onClick={()=>changeView(v)} key={v}>{v==="day"?"일간":v==="week"?"주간":"월간"}</button>)}</div></div>{view==="day"?<DayBoard rooms={activeRooms} reservations={reservations} onCreate={setBooking} onDetail={setDetail} date={date}/>:<PeriodBoard view={view} range={currentRange} reservations={reservations} onDetail={setDetail}/>}</section>}
    {tab==="mine"&&<ReservationList title="내 예약" reservations={mine} onDetail={setDetail}/>} {tab==="recurring"&&<RecurringPanel rooms={activeRooms} recurring={recurring} isAdmin={isAdmin} setMessage={setMessage} onChanged={async()=>{setRecurring(await api("/api/v1/recurring-meetings"));await reload()}}/>}{tab==="rooms"&&isAdmin&&<RoomAdmin rooms={rooms} setMessage={setMessage} onChanged={async()=>setRooms(await api("/api/v1/meeting-rooms?archived=1"))}/>} 
  </div>{booking&&<BookingModal booking={booking} roomName={rooms.find(r=>r.id===booking.roomId)?.name??""} members={members.filter(m=>m.id!==currentUserId)} setBooking={setBooking} onSubmit={submitBooking}/>} {detail&&<DetailModal reservation={detail} canEdit={isAdmin||detail.userId===currentUserId} onClose={()=>setDetail(null)} onCancel={()=>cancel(detail.id)} onChange={()=>changeTime(detail)}/>}</>;
}

function DayBoard({rooms,reservations,onCreate,onDetail,date}:{rooms:Room[];reservations:Reservation[];onCreate:(v:any)=>void;onDetail:(r:Reservation)=>void;date:string}){return <><div className="day-overview"><div><span className="day-overview-label">DAILY SCHEDULE</span><h2>{dateLabel(date)}</h2><p>빈 시간대를 선택하면 바로 예약할 수 있습니다.</p></div><dl><div><dt>운영 회의실</dt><dd>{rooms.length}</dd></div><div><dt>오늘 예약</dt><dd>{reservations.length}</dd></div></dl></div>{rooms.length?<div className="meeting-grid" style={{gridTemplateColumns:`76px repeat(${rooms.length},minmax(170px,1fr))`}}><div className="meeting-time-head"><span>시간</span></div>{rooms.map(r=><div className="meeting-room-head" key={r.id}><span className={`room-type ${r.roomType.toLowerCase()}`}>{r.roomType==="LARGE"?"대회의실":"소회의실"}</span><strong>{r.name}</strong><small>{r.floor??"위치 미정"} · 최대 {r.capacity}명</small></div>)}{SLOTS.map(slot=><div style={{display:"contents"}} key={slot}><time className={slot%60===0?"hour":"half"}>{slot%60===0?hhmm(slot):""}</time>{rooms.map(room=>{const found=reservations.find(r=>r.roomId===room.id&&time(r.startAt)===hhmm(slot)),occupied=reservations.some(r=>r.roomId===room.id&&time(r.startAt)<hhmm(slot)&&time(r.endAt)>hhmm(slot));return found?<button className={`meeting-event ${found.recurring?"recurring":""}`} style={{gridRow:`span ${Math.max(1,(new Date(found.endAt).getTime()-new Date(found.startAt).getTime())/1800000)}`}} onClick={()=>onDetail(found)} key={room.id}><strong>{found.purpose}</strong><small>{time(found.startAt)}–{time(found.endAt)}</small><span>{found.userName} · {found.attendees.length}명</span></button>:occupied?null:<button className="meeting-slot" aria-label={`${room.name} ${hhmm(slot)} 예약`} title={`${hhmm(slot)} 예약하기`} onClick={()=>onCreate({roomId:room.id,date,start:hhmm(slot),end:hhmm(Math.min(slot+60,END)),purpose:"",attendeeIds:[]})} key={room.id}><span>+</span></button>})}</div>)}</div>:<p className="empty meeting-empty">운영 중인 회의실이 없습니다.</p>}</>}
function PeriodBoard({view,range:period,reservations,onDetail}:{view:View;range:{from:string;to:string};reservations:Reservation[];onDetail:(r:Reservation)=>void}){const days=daysBetween(period.from,period.to);return <div className={view==="week"?"meeting-week":"meeting-month"}>{days.map(day=>{const items=reservations.filter(r=>dayKey(r.startAt)===day);return <section className="period-day" key={day}><header><strong>{Number(day.slice(8))}</strong><span>{items.length}건</span></header><div>{items.map(r=><button className="period-event" onClick={()=>onDetail(r)} key={r.id}><time>{time(r.startAt)}</time><strong>{r.roomName}</strong><span>{r.purpose}</span></button>)}</div></section>})}</div>}
function ReservationList({title,reservations,onDetail}:{title:string;reservations:Reservation[];onDetail:(r:Reservation)=>void}){return <section className="panel"><div className="panel-head"><h2>{title}</h2><span>{reservations.length}건</span></div><div className="meeting-list">{reservations.map(r=><button className="reservation-row" onClick={()=>onDetail(r)} key={r.id}><strong>{r.roomName}</strong><span>{dayKey(r.startAt)} {time(r.startAt)}–{time(r.endAt)}</span><span>{r.purpose}</span><small>참석자 {r.attendees.length}명</small></button>)}{!reservations.length&&<p className="empty">예약이 없습니다.</p>}</div></section>}
function BookingModal({booking,roomName,members,setBooking,onSubmit}:{booking:any;roomName:string;members:Member[];setBooking:(v:any)=>void;onSubmit:(e:FormEvent<HTMLFormElement>)=>void}){return <div className="modal-backdrop"><form className="modal-card" onSubmit={onSubmit}><h2>회의실 예약</h2><label>회의실<input value={roomName} disabled/></label><label>예약일<input type="date" value={booking.date} onChange={e=>setBooking({...booking,date:e.target.value})}/></label><div className="form-grid two"><label>시작<input type="time" min="09:00" max="19:00" step="1800" value={booking.start} onChange={e=>setBooking({...booking,start:e.target.value})}/></label><label>종료<input type="time" min="09:00" max="19:00" step="1800" value={booking.end} onChange={e=>setBooking({...booking,end:e.target.value})}/></label></div><label>사용 목적<input required maxLength={500} value={booking.purpose} onChange={e=>setBooking({...booking,purpose:e.target.value})}/></label><fieldset className="attendee-picker"><legend>참석자 선택 ({booking.attendeeIds.length}명)</legend>{members.map(m=><label key={m.id}><input type="checkbox" checked={booking.attendeeIds.includes(m.id)} onChange={e=>setBooking({...booking,attendeeIds:e.target.checked?[...booking.attendeeIds,m.id]:booking.attendeeIds.filter((id:string)=>id!==m.id)})}/>{m.name} <small>({m.userId})</small></label>)}</fieldset><div className="modal-actions"><button type="button" className="button secondary" onClick={()=>setBooking(null)}>닫기</button><button className="button primary">예약</button></div></form></div>}
function DetailModal({reservation,canEdit,onClose,onCancel,onChange}:{reservation:Reservation;canEdit:boolean;onClose:()=>void;onCancel:()=>void;onChange:()=>void}){return <div className="modal-backdrop"><section className="modal-card reservation-detail"><h2>예약 상세</h2><dl><dt>회의실</dt><dd>{reservation.roomName}</dd><dt>일시</dt><dd>{dayKey(reservation.startAt)} {time(reservation.startAt)}–{time(reservation.endAt)}</dd><dt>예약자</dt><dd>{reservation.userName}{reservation.department?` · ${reservation.department}`:""}</dd><dt>사용 목적</dt><dd>{reservation.purpose}</dd><dt>예약 유형</dt><dd>{reservation.recurring?"정기예약":"일반예약"}</dd><dt>참석자</dt><dd>{reservation.attendees.length?reservation.attendees.map(a=>`${a.name}${a.department?`(${a.department})`:""}`).join(", "):"등록된 참석자 없음"}</dd></dl><div className="modal-actions">{canEdit&&<><button className="button secondary" onClick={onChange}>시간 변경</button><button className="button danger" onClick={onCancel}>예약 취소</button></>}<button className="button primary" onClick={onClose}>닫기</button></div></section></div>}

function RecurringPanel({rooms,recurring,isAdmin,setMessage,onChanged}:{rooms:Room[];recurring:Recurring[];isAdmin:boolean;setMessage:(s:string)=>void;onChanged:()=>Promise<void>}){async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/v1/recurring-meetings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({roomId:f.get("roomId"),patternType:f.get("patternType"),daysOfWeek:f.getAll("days").map(Number),dayOfMonth:Number(f.get("dayOfMonth"))||undefined,startMinutes:toMinutes(String(f.get("start"))),endMinutes:toMinutes(String(f.get("end"))),periodStart:f.get("periodStart"),periodEnd:f.get("periodEnd"),purpose:f.get("purpose")})});e.currentTarget.reset();await onChanged();setMessage("정기예약 신청이 접수되었습니다.")}catch(err){setMessage((err as Error).message)}}async function review(id:string,action:"approve"|"reject"){const reason=action==="reject"?prompt("반려 사유")??"":"";try{await api(`/api/v1/recurring-meetings/${id}/review`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,reason})});await onChanged();setMessage("처리되었습니다.")}catch(err){setMessage((err as Error).message)}}return <div className="meeting-split">{!isAdmin&&<form className="panel meeting-form" onSubmit={submit}><h2>정기예약 신청</h2><label>회의실<select name="roomId">{rooms.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select></label><label>반복<select name="patternType"><option value="WEEKLY">매주</option><option value="DAILY">매일</option><option value="MONTHLY">매월</option></select></label><fieldset><legend>요일</legend>{[1,2,3,4,5,6,7].map((d,i)=><label className="check" key={d}><input type="checkbox" name="days" value={d}/>{"월화수목금토일"[i]}</label>)}</fieldset><label>매월 일자<input name="dayOfMonth" type="number" min="1" max="31"/></label><div className="form-grid two"><label>시작<input name="start" type="time" defaultValue="10:00" required/></label><label>종료<input name="end" type="time" defaultValue="11:00" required/></label><label>기간 시작<input name="periodStart" type="date" required/></label><label>기간 종료<input name="periodEnd" type="date" required/></label></div><label>목적<input name="purpose" required/></label><button className="button primary">신청</button></form>}<section className="panel"><div className="panel-head"><h2>{isAdmin?"승인 요청":"신청 내역"}</h2><span>{recurring.length}건</span></div><div className="meeting-list">{recurring.map(r=><article key={r.id}><div><strong>{r.room.name} · {r.applicant.name}</strong><p>{r.patternType} · {hhmm(r.startMinutes)}–{hhmm(r.endMinutes)} · {r.purpose} · {r.status}</p></div>{isAdmin&&r.status==="PENDING"&&<div><button className="button primary" onClick={()=>review(r.id,"approve")}>승인</button> <button className="button danger" onClick={()=>review(r.id,"reject")}>반려</button></div>}</article>)}</div></section></div>}
const toMinutes=(value:string)=>{const[h,m]=value.split(":").map(Number);return h*60+m};
function RoomAdmin({rooms,setMessage,onChanged}:{rooms:Room[];setMessage:(s:string)=>void;onChanged:()=>Promise<void>}){async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);try{await api("/api/v1/meeting-rooms",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.get("name"),roomType:f.get("roomType"),capacity:Number(f.get("capacity")),floor:f.get("floor")||null,equipment:String(f.get("equipment")||"").split(",").map(x=>x.trim()).filter(Boolean)})});e.currentTarget.reset();await onChanged();setMessage("회의실을 추가했습니다.")}catch(err){setMessage((err as Error).message)}}async function remove(r:Room){if(!confirm(`${r.name}을 삭제하시겠습니까?`))return;try{const result=await api(`/api/v1/meeting-rooms/${r.id}`,{method:"DELETE"});await onChanged();setMessage(result.mode==="archived"?"보관 처리했습니다.":"삭제했습니다.")}catch(err){setMessage((err as Error).message)}}async function restore(id:string){await api(`/api/v1/meeting-rooms/${id}/restore`,{method:"POST"});await onChanged()}return <div className="meeting-split"><form className="panel meeting-form" onSubmit={create}><h2>회의실 추가</h2><label>이름<input name="name" required/></label><div className="form-grid two"><label>유형<select name="roomType"><option value="SMALL">소회의실</option><option value="LARGE">대회의실</option></select></label><label>인원<input name="capacity" type="number" min="1" defaultValue="6"/></label></div><label>위치<input name="floor"/></label><label>장비<input name="equipment"/></label><button className="button primary">추가</button></form><section className="panel"><div className="meeting-list">{rooms.map(r=><article className={r.deletedAt?"archived":""} key={r.id}><div><strong>{r.name}</strong><p>{r.capacity}명 · {r.floor??"-"}</p></div>{r.deletedAt?<button className="button secondary" onClick={()=>restore(r.id)}>복원</button>:<button className="button danger" onClick={()=>remove(r)}>삭제</button>}</article>)}</div></section></div>}
